<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Octavia Steiger">
<meta name="dcterms.date" content="2026-04-06">

<title>Winter Olympics Medal Analysis</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="blog_files/libs/clipboard/clipboard.min.js"></script>
<script src="blog_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="blog_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="blog_files/libs/quarto-html/popper.min.js"></script>
<script src="blog_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="blog_files/libs/quarto-html/anchor.min.js"></script>
<link href="blog_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="blog_files/libs/quarto-html/quarto-syntax-highlighting-a06763021a52c43c40a351ac8b799b8f.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="blog_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="blog_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="blog_files/libs/bootstrap/bootstrap-f93d581b41f20e53031fef139986cb6a.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-full">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Contents</h2>
   
  <ul class="collapse">
  <li><a href="#why-does-norway-win-so-much" id="toc-why-does-norway-win-so-much" class="nav-link active" data-scroll-target="#why-does-norway-win-so-much">Why does Norway win so much?</a></li>
  <li><a href="#the-data" id="toc-the-data" class="nav-link" data-scroll-target="#the-data">1. The data</a></li>
  <li><a href="#building-the-dataset" id="toc-building-the-dataset" class="nav-link" data-scroll-target="#building-the-dataset">2. Building the dataset</a></li>
  <li><a href="#a-century-of-dominance" id="toc-a-century-of-dominance" class="nav-link" data-scroll-target="#a-century-of-dominance">3. A century of dominance</a></li>
  <li><a href="#does-money-buy-medals" id="toc-does-money-buy-medals" class="nav-link" data-scroll-target="#does-money-buy-medals">4. Does money buy medals?</a></li>
  <li><a href="#the-home-advantage" id="toc-the-home-advantage" class="nav-link" data-scroll-target="#the-home-advantage">5. The home advantage</a></li>
  <li><a href="#the-fallen-powers" id="toc-the-fallen-powers" class="nav-link" data-scroll-target="#the-fallen-powers">6. The fallen powers</a></li>
  <li><a href="#the-full-picture-regression-results" id="toc-the-full-picture-regression-results" class="nav-link" data-scroll-target="#the-full-picture-regression-results">7. The full picture: regression results</a></li>
  <li><a href="#conclusions" id="toc-conclusions" class="nav-link" data-scroll-target="#conclusions">8. Conclusions</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="../blog.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
</div>
<main class="content column-page-left" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Winter Olympics Medal Analysis</h1>
</div>



<div class="quarto-title-meta column-page-left">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Octavia Steiger </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">April 6, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="why-does-norway-win-so-much" class="level2">
<h2 class="anchored" data-anchor-id="why-does-norway-win-so-much">Why does Norway win so much?</h2>
<p>Norway has a population of just 5 million people, yet it sits at the top of the all-time Winter Olympic medal table with 318 medals, more than 40 ahead of the United States despite the US having around 60 times the population. So what’s going on?</p>
<p>To find out, I looked at data from every Winter Olympic Games since Chamonix 1924, testing three possible explanations: wealth, population size and home advantage. The short answer: all three matter just not equally.</p>
<p>Before diving into the results, it helps to understand exactly what data sits behind this analysis and how it was built.</p>
<p><em>The pipeline: scrape –&gt; clean –&gt; merge with World Bank data –&gt; analyse –&gt; visualise</em></p>
<hr>
</section>
<section id="the-data" class="level2">
<h2 class="anchored" data-anchor-id="the-data">1. The data</h2>
<p>I used two main datasets for this, one tracking Olympic medal outcomes going back a century, and one capturing the economic context behind each competing nation.</p>
<section id="olympic-medals-olympedia" class="level4">
<h4 class="anchored" data-anchor-id="olympic-medals-olympedia">Olympic Medals (Olympedia):</h4>
<p>Scraped from <a href="https://www.olympedia.org/">Olympedia</a>, covering all 24 Winter Games from Chamonix 1924 to Beijing 2022. Each row represents one country’s performance in a single Games (1,163 country-year observations in total).</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Variable</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>NOC</code></td>
<td>National Olympic Committee country code</td>
</tr>
<tr class="even">
<td><code>Year</code></td>
<td>Olympic Year (1924 - 2022)</td>
</tr>
<tr class="odd">
<td><code>Gold / Silver / Bronze</code></td>
<td>Medal counts for that Games</td>
</tr>
<tr class="even">
<td><code>Total</code></td>
<td>Sum of all medals won</td>
</tr>
<tr class="odd">
<td><code>Host</code></td>
<td>1 if the country hosted that year, 0 otherwise</td>
</tr>
</tbody>
</table>
</section>
<section id="economic-indicators-world-bank" class="level4">
<h4 class="anchored" data-anchor-id="economic-indicators-world-bank">Economic Indicators (World Bank):</h4>
<p>GDP per capita (Current USD, indicator <code>NY.GDP.PCAP.CD</code>) and population (<code>SP.POP.TOTL</code>) fetched via the World Bank API, then matched to each country-year in the medals dataset.</p>
<blockquote class="blockquote">
<p><strong>A note on tied medals:</strong> In 27 events where multiple athletes tied for the same medal position, each tied nation received full medal credit, consistent with how the IOC handles ties in official records.</p>
</blockquote>
<hr>
</section>
</section>
<section id="building-the-dataset" class="level2">
<h2 class="anchored" data-anchor-id="building-the-dataset">2. Building the dataset</h2>
<section id="collecting-the-medal-data" class="level3">
<h3 class="anchored" data-anchor-id="collecting-the-medal-data">2.1 Collecting the Medal Data</h3>
<p>Official Olympic data was not available as a download, so the data had to be scraped directly from Olympedia (https://www.olympedia.org).</p>
<p>I built a web scraper (<code>scrape.py</code>) that fetched the medal table for each of the 24 Winter Olympic Games. Each page returned an HTML table listing every event alongside gold, silver and bronze medalists and their countries.</p>
<p>The raw data came back wide, with separate columns per medal, country names in inconsistent formats, sports category headings mixed into the results rows and combined NOC codes where medals were tied.</p>
<p>Not all NOCs appear in each Games, the number of competing nations has grown over time, from around 19 nations in 1924 to over 90 today.</p>
<div id="18b0b816" class="cell" data-execution_count="1">
<details class="code-fold">
<summary>Show code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>medals <span class="op">=</span> pd.read_csv(<span class="st">'../data/clean/medals_clean.csv'</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="bu">len</span>(medals)<span class="sc">}</span><span class="ss"> events scraped across </span><span class="sc">{</span>medals[<span class="st">'year'</span>]<span class="sc">.</span>nunique()<span class="sc">}</span><span class="ss"> Games"</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>medals.head(<span class="dv">10</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>1163 events scraped across 24 Games</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="1">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">year</th>
<th data-quarto-table-cell-role="th">sport</th>
<th data-quarto-table-cell-role="th">event</th>
<th data-quarto-table-cell-role="th">gold_name</th>
<th data-quarto-table-cell-role="th">gold_noc</th>
<th data-quarto-table-cell-role="th">tie_gold</th>
<th data-quarto-table-cell-role="th">silver_name</th>
<th data-quarto-table-cell-role="th">silver_noc</th>
<th data-quarto-table-cell-role="th">tie_silver</th>
<th data-quarto-table-cell-role="th">bronze_name</th>
<th data-quarto-table-cell-role="th">bronze_noc</th>
<th data-quarto-table-cell-role="th">tie_bronze</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>1924</td>
<td>Alpinism</td>
<td>Alpinism, Open</td>
<td>Mixed team</td>
<td>MIX</td>
<td>False</td>
<td>—</td>
<td>—</td>
<td>False</td>
<td>—</td>
<td>—</td>
<td>False</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>1924</td>
<td>Bobsleigh</td>
<td>Four, Men</td>
<td>Switzerland 1</td>
<td>SUI</td>
<td>False</td>
<td>Great Britain 1</td>
<td>GBR</td>
<td>False</td>
<td>Belgium 1</td>
<td>BEL</td>
<td>False</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>1924</td>
<td>Cross Country Skiing</td>
<td>18 kilometres, Men</td>
<td>Thorleif Haug</td>
<td>NOR</td>
<td>False</td>
<td>Johan Grøttumsbraaten</td>
<td>NOR</td>
<td>False</td>
<td>Tapani Niku</td>
<td>FIN</td>
<td>False</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>1924</td>
<td>Cross Country Skiing</td>
<td>50 kilometres, Men</td>
<td>Thorleif Haug</td>
<td>NOR</td>
<td>False</td>
<td>Thoralf Strømstad</td>
<td>NOR</td>
<td>False</td>
<td>Johan Grøttumsbraaten</td>
<td>NOR</td>
<td>False</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>1924</td>
<td>Curling</td>
<td>Team, Men</td>
<td>Great Britain</td>
<td>GBR</td>
<td>False</td>
<td>Sweden</td>
<td>SWE</td>
<td>False</td>
<td>France</td>
<td>FRA</td>
<td>False</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>1924</td>
<td>Figure Skating</td>
<td>Singles, Men</td>
<td>Gillis Grafström</td>
<td>SWE</td>
<td>False</td>
<td>Willy Böckl</td>
<td>AUT</td>
<td>False</td>
<td>Georges Gautschi</td>
<td>SUI</td>
<td>False</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>1924</td>
<td>Figure Skating</td>
<td>Singles, Women</td>
<td>Herma Planck-Szabo</td>
<td>AUT</td>
<td>False</td>
<td>Beatrix Loughran</td>
<td>USA</td>
<td>False</td>
<td>Ethel Muckelt</td>
<td>GBR</td>
<td>False</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">7</th>
<td>1924</td>
<td>Figure Skating</td>
<td>Pairs, Mixed</td>
<td>Austria</td>
<td>AUT</td>
<td>False</td>
<td>Finland</td>
<td>FIN</td>
<td>False</td>
<td>France 1</td>
<td>FRA</td>
<td>False</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">8</th>
<td>1924</td>
<td>Ice Hockey</td>
<td>Ice Hockey, Men</td>
<td>Canada</td>
<td>CAN</td>
<td>False</td>
<td>United States</td>
<td>USA</td>
<td>False</td>
<td>Great Britain</td>
<td>GBR</td>
<td>False</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">9</th>
<td>1924</td>
<td>Military Ski Patrol</td>
<td>Military Ski Patrol, Men</td>
<td>Switzerland</td>
<td>SUI</td>
<td>False</td>
<td>Finland</td>
<td>FIN</td>
<td>False</td>
<td>France</td>
<td>FRA</td>
<td>False</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
<section id="cleaning-the-data" class="level3">
<h3 class="anchored" data-anchor-id="cleaning-the-data">2.2 Cleaning the Data</h3>
<section id="sorting-out-the-sport-categories" class="level4">
<h4 class="anchored" data-anchor-id="sorting-out-the-sport-categories">Sorting out the sport categories</h4>
<p>The scraped HTML table included two types of rows: actual event results and section headings that just said the sport name. These headings were not real results, they had no medalists data or NOC codes, however they did have the sport name of each event which is information I still needed.</p>
<p>In <code>clean.py</code>, I identified the heading rows (any row where all medal columns were empty), extracted the sport name, forward filled it down to all the event rows below, then dropped the headings.</p>
<div id="fa969b2b" class="cell" data-execution_count="2">
<details class="code-fold">
<summary>Show code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Sports present in the dataset:"</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="bu">sorted</span>(medals[<span class="st">'sport'</span>].dropna().unique().tolist()))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Sports present in the dataset:
['Alpine Skiing', 'Alpinism', 'Biathlon', 'Bobsleigh', 'Cross Country Skiing', 'Curling', 'Figure Skating', 'Freestyle Skiing', 'Ice Hockey', 'Luge', 'Military Ski Patrol', 'Nordic Combined', 'Short Track Speed Skating', 'Skeleton', 'Ski Jumping', 'Snowboarding', 'Speed Skating']</code></pre>
</div>
</div>
</section>
<section id="dealing-with-tied-medals" class="level4">
<h4 class="anchored" data-anchor-id="dealing-with-tied-medals">Dealing with tied medals</h4>
<p>Occasionally there were two countries that shared a podium position, for example two gold medalists and no silver. In the raw data these appear as a single combined entry in the NOC column rather than as two seperate rows.</p>
<p>These needed to be detected and split into two rows, otherwise any country-level analysis would be inaccurate. Within the cleaning step these are flagged using the <code>tie</code> columns and then are split into seperate rows in a later step in the pipeline, so that both countries get the credit for the medal in the analysis.</p>
<div id="1cb46cef" class="cell" data-execution_count="3">
<details class="code-fold">
<summary>Show code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>tied <span class="op">=</span> medals[medals[<span class="st">'tie_gold'</span>] <span class="op">|</span> medals[<span class="st">'tie_silver'</span>] <span class="op">|</span> medals[<span class="st">'tie_bronze'</span>]]</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Events with at least one tied medal: </span><span class="sc">{</span><span class="bu">len</span>(tied)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>tied[[<span class="st">'year'</span>, <span class="st">'sport'</span>, <span class="st">'event'</span>, <span class="st">'tie_gold'</span>, <span class="st">'tie_silver'</span>, <span class="st">'tie_bronze'</span>]].head(<span class="dv">8</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Events with at least one tied medal: 27</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="3">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">year</th>
<th data-quarto-table-cell-role="th">sport</th>
<th data-quarto-table-cell-role="th">event</th>
<th data-quarto-table-cell-role="th">tie_gold</th>
<th data-quarto-table-cell-role="th">tie_silver</th>
<th data-quarto-table-cell-role="th">tie_bronze</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">12</th>
<td>1924</td>
<td>Speed Skating</td>
<td>500 metres, Men</td>
<td>False</td>
<td>False</td>
<td>True</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">27</th>
<td>1928</td>
<td>Speed Skating</td>
<td>500 metres, Men</td>
<td>True</td>
<td>False</td>
<td>False</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">61</th>
<td>1948</td>
<td>Alpine Skiing</td>
<td>Downhill, Men</td>
<td>False</td>
<td>False</td>
<td>True</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">101</th>
<td>1952</td>
<td>Speed Skating</td>
<td>500 metres, Men</td>
<td>False</td>
<td>False</td>
<td>True</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">126</th>
<td>1956</td>
<td>Speed Skating</td>
<td>1,500 metres, Men</td>
<td>True</td>
<td>False</td>
<td>False</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">149</th>
<td>1960</td>
<td>Speed Skating</td>
<td>1,500 metres, Men</td>
<td>True</td>
<td>False</td>
<td>False</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">160</th>
<td>1964</td>
<td>Alpine Skiing</td>
<td>Giant Slalom, Women</td>
<td>False</td>
<td>True</td>
<td>False</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">174</th>
<td>1964</td>
<td>Figure Skating</td>
<td>Pairs, Mixed</td>
<td>False</td>
<td>True</td>
<td>False</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>There are relatively few, but they matter. :::{.callout-tip} ## Why this matters Ignoring ties would undercount medals for countries involved. Splitting them into seperate rows ensures every nation gets full credit which is consistent with how the IOC handles ties in official records. :::</p>
</section>
</section>
<section id="adding-economic-context" class="level3">
<h3 class="anchored" data-anchor-id="adding-economic-context">2.3 Adding Economic Context</h3>
<p>To test whether wealth or population drives success, each medal row needed to be merged with GDP and population data for the corresponding year.</p>
<section id="why-i-used-the-world-bank-api" class="level4">
<h4 class="anchored" data-anchor-id="why-i-used-the-world-bank-api">Why I used the World Bank API</h4>
<p>I needed two indicators for each country and year: GDP per capita and population size. Both indicators were fetched from the World Bank API (https://data.worldbank.org/) using the <code>wbgapi</code> package, which gave clean, standardised data without additional formating work.</p>
</section>
<section id="the-noc-to-isc-problem" class="level4">
<h4 class="anchored" data-anchor-id="the-noc-to-isc-problem">The NOC to ISC problem</h4>
<p>There was however a problem with merging the medal data with the World Bank data, as the medal data uses NOC codes to identify countries, whereas the World Bank data uses ISO country codes. This required a lookup table mapping each NOC to its closest modern equivalent, since some NOCs no longer exist or have since split into multiple countries.</p>
<p>The trickiest cases were the Soviet Union (URS), East Germany (GDR) and Yugoslavia (YUG) which are all heavy medal winners that no longer exist. For these I mapped to their largest successor state (Russia, Germany and Serbia) where economic data was available and excluded rows where I could not make a reasonable match.</p>
</section>
<section id="merging-the-datasets" class="level4">
<h4 class="anchored" data-anchor-id="merging-the-datasets">Merging the datasets</h4>
<p>Once both datasets used the same country codes, they were joined on country and year, giving a single dataset with two additional columns:</p>
<ul>
<li><strong><code>is_host</code></strong> : a flag marking whether the winning country was hosting the games that year, to test the impact of home advantage</li>
<li><strong><code>log_gdp_per_capita</code></strong> and <strong><code>log_population</code></strong>: I took the log of both to account for diminishing returns, the gap between a poor and a morderately wealthy country matters more than the same gap at the top end of the scale.</li>
</ul>
<div id="9889666a" class="cell" data-execution_count="4">
<details class="code-fold">
<summary>Show code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>final <span class="op">=</span> pd.read_csv(<span class="st">"../data/clean/worldbank_final.csv"</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Final merged dataset: </span><span class="sc">{</span><span class="bu">len</span>(final)<span class="sc">}</span><span class="ss"> medal rows"</span>)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>final.head(<span class="dv">8</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Final merged dataset: 3493 medal rows</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="4">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">year</th>
<th data-quarto-table-cell-role="th">event</th>
<th data-quarto-table-cell-role="th">noc</th>
<th data-quarto-table-cell-role="th">medal</th>
<th data-quarto-table-cell-role="th">iso_code</th>
<th data-quarto-table-cell-role="th">gdp_per_capita</th>
<th data-quarto-table-cell-role="th">population</th>
<th data-quarto-table-cell-role="th">host_noc</th>
<th data-quarto-table-cell-role="th">is_host</th>
<th data-quarto-table-cell-role="th">log_gdp_per_capita</th>
<th data-quarto-table-cell-role="th">log_population</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>1924</td>
<td>Singles, Women</td>
<td>AUT</td>
<td>gold</td>
<td>AUT</td>
<td>NaN</td>
<td>NaN</td>
<td>FRA</td>
<td>0</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>1924</td>
<td>Pairs, Mixed</td>
<td>AUT</td>
<td>gold</td>
<td>AUT</td>
<td>NaN</td>
<td>NaN</td>
<td>FRA</td>
<td>0</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>1924</td>
<td>Singles, Men</td>
<td>AUT</td>
<td>silver</td>
<td>AUT</td>
<td>NaN</td>
<td>NaN</td>
<td>FRA</td>
<td>0</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>1924</td>
<td>Four, Men</td>
<td>BEL</td>
<td>bronze</td>
<td>BEL</td>
<td>NaN</td>
<td>NaN</td>
<td>FRA</td>
<td>0</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>1924</td>
<td>Ice Hockey, Men</td>
<td>CAN</td>
<td>gold</td>
<td>CAN</td>
<td>NaN</td>
<td>NaN</td>
<td>FRA</td>
<td>0</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>1924</td>
<td>18 kilometres, Men</td>
<td>FIN</td>
<td>bronze</td>
<td>FIN</td>
<td>NaN</td>
<td>NaN</td>
<td>FRA</td>
<td>0</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>1924</td>
<td>Allround, Men</td>
<td>FIN</td>
<td>bronze</td>
<td>FIN</td>
<td>NaN</td>
<td>NaN</td>
<td>FRA</td>
<td>0</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">7</th>
<td>1924</td>
<td>500 metres, Men</td>
<td>FIN</td>
<td>bronze</td>
<td>FIN</td>
<td>NaN</td>
<td>NaN</td>
<td>FRA</td>
<td>0</td>
<td>NaN</td>
<td>NaN</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="072be0b0" class="cell" data-execution_count="5">
<details class="code-fold">
<summary>Show code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>missing <span class="op">=</span> final[<span class="st">'gdp_per_capita'</span>].isna().<span class="bu">sum</span>()</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>total <span class="op">=</span> <span class="bu">len</span>(final)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Rows with missing GDP per capita: </span><span class="sc">{</span>missing<span class="sc">}</span><span class="ss"> (</span><span class="sc">{</span><span class="dv">100</span> <span class="op">*</span> missing <span class="op">/</span> total<span class="sc">:.1f}</span><span class="ss">%)'</span>)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'These are mostly historic NOCs'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Rows with missing GDP per capita: 567 (16.2%)
These are mostly historic NOCs</code></pre>
</div>
</div>
<p>The missing GDP rows are expected and unavoidable, as many of the older NOCs no longer exist and therefore do not have corresponding economic data in the World Bank dataset. Therefore, I excluded these rows from the regression but kept in the raw medal count so the all-time table remains accurate.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Data limitation
</div>
</div>
<div class="callout-body-container callout-body">
<p>Around 16% of medal rows are missing GDP data, mostly from historical NOCs that no longer exist (URS, GDR, YUG). These are excluded from the regression but kept in the all-time medal counts so historical totals remain accurate.</p>
</div>
</div>
<hr>
</section>
</section>
</section>
<section id="a-century-of-dominance" class="level2">
<h2 class="anchored" data-anchor-id="a-century-of-dominance">3. A century of dominance</h2>
<div id="2703c60e" class="cell" data-execution_count="6">
<details class="code-fold">
<summary>Show code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>sns.set_theme(style<span class="op">=</span><span class="st">'whitegrid'</span>, font_scale<span class="op">=</span><span class="fl">1.1</span>)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>GOLD   <span class="op">=</span> <span class="st">"#FFD700"</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>SILVER <span class="op">=</span> <span class="st">"#C0C0C0"</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>BRONZE <span class="op">=</span> <span class="st">"#CD7F32"</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>BLUE   <span class="op">=</span> <span class="st">"#1f77b4"</span></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>alltime <span class="op">=</span> pd.read_csv(<span class="st">"../data/clean/alltime_table.csv"</span>)</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>cy      <span class="op">=</span> pd.read_csv(<span class="st">"../data/clean/medals_country_year.csv"</span>)</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>reg     <span class="op">=</span> pd.read_csv(<span class="st">"../outputs/regression_results.csv"</span>)</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>final   <span class="op">=</span> pd.read_csv(<span class="st">"../data/clean/worldbank_final.csv"</span>)</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>NOC_NAMES <span class="op">=</span> {</span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a>    <span class="st">'NOR'</span>: <span class="st">'Norway'</span>,    <span class="st">'USA'</span>: <span class="st">'United States'</span>, <span class="st">'AUT'</span>: <span class="st">'Austria'</span>,</span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a>    <span class="st">'GER'</span>: <span class="st">'Germany'</span>,   <span class="st">'FIN'</span>: <span class="st">'Finland'</span>,       <span class="st">'SWE'</span>: <span class="st">'Sweden'</span>,</span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a>    <span class="st">'SUI'</span>: <span class="st">'Switzerland'</span>,<span class="st">'RUS'</span>: <span class="st">'Russia'</span>,        <span class="st">'CAN'</span>: <span class="st">'Canada'</span>,</span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a>    <span class="st">'ITA'</span>: <span class="st">'Italy'</span>,     <span class="st">'FRA'</span>: <span class="st">'France'</span>,         <span class="st">'NED'</span>: <span class="st">'Netherlands'</span>,</span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a>    <span class="st">'GDR'</span>: <span class="st">'East Germany'</span>,<span class="st">'URS'</span>: <span class="st">'Soviet Union'</span>, <span class="st">'TCH'</span>: <span class="st">'Czechoslovakia'</span>,</span>
<span id="cb11-20"><a href="#cb11-20" aria-hidden="true" tabindex="-1"></a>    <span class="st">'EUN'</span>: <span class="st">'Unified Team'</span>,<span class="st">'JPN'</span>: <span class="st">'Japan'</span>,        <span class="st">'KOR'</span>: <span class="st">'South Korea'</span>,</span>
<span id="cb11-21"><a href="#cb11-21" aria-hidden="true" tabindex="-1"></a>    <span class="st">'CZE'</span>: <span class="st">'Czech Republic'</span>,<span class="st">'POL'</span>: <span class="st">'Poland'</span>,     <span class="st">'GBR'</span>: <span class="st">'Great Britain'</span>,</span>
<span id="cb11-22"><a href="#cb11-22" aria-hidden="true" tabindex="-1"></a>    <span class="st">'BEL'</span>: <span class="st">'Belgium'</span>,   <span class="st">'YUG'</span>: <span class="st">'Yugoslavia'</span>,    <span class="st">'LIE'</span>: <span class="st">'Liechtenstein'</span>,</span>
<span id="cb11-23"><a href="#cb11-23" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>The table below shows the 15 most decorated nations, ranked by total medals.</p>
<div id="fc7d3789" class="cell" data-execution_count="7">
<details class="code-fold">
<summary>Show code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>summary <span class="op">=</span> pd.read_csv(<span class="st">'../outputs/summary_stats.csv'</span>, index_col<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>summary.style.set_caption(<span class="st">'Table 1: Top 15 nations by total Winter Olympic Medals'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="7">
<style type="text/css">
</style>

<div id="T_8afb2" class="quarto-float quarto-figure quarto-figure-center anchored" data-quarto-postprocess="true">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="T_8afb2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Table 1: Top 15 nations by total Winter Olympic Medals
</figcaption>
<div aria-describedby="T_8afb2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table id="T_8afb2" class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th class="blank level0" data-quarto-table-cell-role="th">&nbsp;</th>
<th id="T_8afb2_level0_col0" class="col_heading level0 col0" data-quarto-table-cell-role="th">Avg Medals/games</th>
<th id="T_8afb2_level0_col1" class="col_heading level0 col1" data-quarto-table-cell-role="th">Total medals</th>
<th id="T_8afb2_level0_col2" class="col_heading level0 col2" data-quarto-table-cell-role="th">Games Attended</th>
</tr>
<tr class="even">
<th class="index_name level0" data-quarto-table-cell-role="th">noc</th>
<th class="blank col0" data-quarto-table-cell-role="th">&nbsp;</th>
<th class="blank col1" data-quarto-table-cell-role="th">&nbsp;</th>
<th class="blank col2" data-quarto-table-cell-role="th">&nbsp;</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th id="T_8afb2_level0_row0" class="row_heading level0 row0" data-quarto-table-cell-role="th">NOR</th>
<td id="T_8afb2_row0_col0" class="data row0 col0">18.700000</td>
<td id="T_8afb2_row0_col1" class="data row0 col1">318</td>
<td id="T_8afb2_row0_col2" class="data row0 col2">17</td>
</tr>
<tr class="even">
<th id="T_8afb2_level0_row1" class="row_heading level0 row1" data-quarto-table-cell-role="th">USA</th>
<td id="T_8afb2_row1_col0" class="data row1 col0">16.200000</td>
<td id="T_8afb2_row1_col1" class="data row1 col1">275</td>
<td id="T_8afb2_row1_col2" class="data row1 col2">17</td>
</tr>
<tr class="odd">
<th id="T_8afb2_level0_row2" class="row_heading level0 row2" data-quarto-table-cell-role="th">GER</th>
<td id="T_8afb2_row2_col0" class="data row2 col0">24.400000</td>
<td id="T_8afb2_row2_col1" class="data row2 col1">268</td>
<td id="T_8afb2_row2_col2" class="data row2 col2">11</td>
</tr>
<tr class="even">
<th id="T_8afb2_level0_row3" class="row_heading level0 row3" data-quarto-table-cell-role="th">AUT</th>
<td id="T_8afb2_row3_col0" class="data row3 col0">12.400000</td>
<td id="T_8afb2_row3_col1" class="data row3 col1">211</td>
<td id="T_8afb2_row3_col2" class="data row3 col2">17</td>
</tr>
<tr class="odd">
<th id="T_8afb2_level0_row4" class="row_heading level0 row4" data-quarto-table-cell-role="th">CAN</th>
<td id="T_8afb2_row4_col0" class="data row4 col0">12.200000</td>
<td id="T_8afb2_row4_col1" class="data row4 col1">207</td>
<td id="T_8afb2_row4_col2" class="data row4 col2">17</td>
</tr>
<tr class="even">
<th id="T_8afb2_level0_row5" class="row_heading level0 row5" data-quarto-table-cell-role="th">NED</th>
<td id="T_8afb2_row5_col0" class="data row5 col0">9.000000</td>
<td id="T_8afb2_row5_col1" class="data row5 col1">144</td>
<td id="T_8afb2_row5_col2" class="data row5 col2">16</td>
</tr>
<tr class="odd">
<th id="T_8afb2_level0_row6" class="row_heading level0 row6" data-quarto-table-cell-role="th">SUI</th>
<td id="T_8afb2_row6_col0" class="data row6 col0">8.900000</td>
<td id="T_8afb2_row6_col1" class="data row6 col1">142</td>
<td id="T_8afb2_row6_col2" class="data row6 col2">16</td>
</tr>
<tr class="even">
<th id="T_8afb2_level0_row7" class="row_heading level0 row7" data-quarto-table-cell-role="th">SWE</th>
<td id="T_8afb2_row7_col0" class="data row7 col0">8.000000</td>
<td id="T_8afb2_row7_col1" class="data row7 col1">136</td>
<td id="T_8afb2_row7_col2" class="data row7 col2">17</td>
</tr>
<tr class="odd">
<th id="T_8afb2_level0_row8" class="row_heading level0 row8" data-quarto-table-cell-role="th">ITA</th>
<td id="T_8afb2_row8_col0" class="data row8 col0">7.900000</td>
<td id="T_8afb2_row8_col1" class="data row8 col1">135</td>
<td id="T_8afb2_row8_col2" class="data row8 col2">17</td>
</tr>
<tr class="even">
<th id="T_8afb2_level0_row9" class="row_heading level0 row9" data-quarto-table-cell-role="th">FIN</th>
<td id="T_8afb2_row9_col0" class="data row9 col0">7.600000</td>
<td id="T_8afb2_row9_col1" class="data row9 col1">129</td>
<td id="T_8afb2_row9_col2" class="data row9 col2">17</td>
</tr>
<tr class="odd">
<th id="T_8afb2_level0_row10" class="row_heading level0 row10" data-quarto-table-cell-role="th">FRA</th>
<td id="T_8afb2_row10_col0" class="data row10 col0">7.400000</td>
<td id="T_8afb2_row10_col1" class="data row10 col1">126</td>
<td id="T_8afb2_row10_col2" class="data row10 col2">17</td>
</tr>
<tr class="even">
<th id="T_8afb2_level0_row11" class="row_heading level0 row11" data-quarto-table-cell-role="th">RUS</th>
<td id="T_8afb2_row11_col0" class="data row11 col0">19.700000</td>
<td id="T_8afb2_row11_col1" class="data row11 col1">118</td>
<td id="T_8afb2_row11_col2" class="data row11 col2">6</td>
</tr>
<tr class="odd">
<th id="T_8afb2_level0_row12" class="row_heading level0 row12" data-quarto-table-cell-role="th">GDR</th>
<td id="T_8afb2_row12_col0" class="data row12 col0">18.300000</td>
<td id="T_8afb2_row12_col1" class="data row12 col1">110</td>
<td id="T_8afb2_row12_col2" class="data row12 col2">6</td>
</tr>
<tr class="even">
<th id="T_8afb2_level0_row13" class="row_heading level0 row13" data-quarto-table-cell-role="th">KOR</th>
<td id="T_8afb2_row13_col0" class="data row13 col0">8.800000</td>
<td id="T_8afb2_row13_col1" class="data row13 col1">79</td>
<td id="T_8afb2_row13_col2" class="data row13 col2">9</td>
</tr>
<tr class="odd">
<th id="T_8afb2_level0_row14" class="row_heading level0 row14" data-quarto-table-cell-role="th">CHN</th>
<td id="T_8afb2_row14_col0" class="data row14 col0">8.600000</td>
<td id="T_8afb2_row14_col1" class="data row14 col1">77</td>
<td id="T_8afb2_row14_col2" class="data row14 col2">9</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</div>
</div>
<p>Norway and the United States lead on total medals, both attending all 17 Games in the dataset. However, the average medals per Games column tells a more interesting story, by sorting by average medals rather than totals it reshuffles the rankings considerably.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Germany and the Cold War nations
</div>
</div>
<div class="callout-body-container callout-body">
<p>Germany’s average of 24.4 medals per Games is the highest in the table desipte having only 11 appearances. This highlights how dominant West Germany and later reunified Germany have been when they competed. Russia (6 Games, 19.7 avg) and East Germany (6 Games, 18.3 avg) show even higher rates, however both stop competing after the Soviet era ended.</p>
</div>
</div>
<p>The chart below shows cumulative medals since 1924 across the top 20 nations. Norway’s bar is noteably gold, showing it doesn’t just compete but consistently wins. The US and Germany follow, both benefiting from size and long-term investment in winter sport.</p>
<div id="cell-fig-alltime" class="cell" data-execution_count="8">
<details class="code-fold">
<summary>Show code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>alltime[<span class="st">'country'</span>] <span class="op">=</span> alltime[<span class="st">'noc'</span>].<span class="bu">map</span>(NOC_NAMES).fillna(alltime[<span class="st">'noc'</span>])</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="dv">9</span>))</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>ax.barh(alltime[<span class="st">'country'</span>], alltime[<span class="st">'gold_medals'</span>], label<span class="op">=</span><span class="st">'Gold'</span>, color<span class="op">=</span>GOLD, height<span class="op">=</span><span class="fl">0.6</span>)</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>ax.barh(alltime[<span class="st">'country'</span>], alltime[<span class="st">'silver_medals'</span>], label<span class="op">=</span><span class="st">'Silver'</span>, color<span class="op">=</span>SILVER, height<span class="op">=</span><span class="fl">0.6</span>, left<span class="op">=</span>alltime[<span class="st">'gold_medals'</span>])</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>ax.barh(alltime[<span class="st">'country'</span>], alltime[<span class="st">'bronze_medals'</span>], label<span class="op">=</span><span class="st">'Bronze'</span>, color<span class="op">=</span>BRONZE, height<span class="op">=</span><span class="fl">0.6</span>, left<span class="op">=</span>alltime[<span class="st">'gold_medals'</span>] <span class="op">+</span> alltime[<span class="st">'silver_medals'</span>])</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>ax.invert_yaxis()</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"All time Winter Olympics Medal Table (top 20)"</span>, fontsize<span class="op">=</span><span class="dv">14</span>, pad<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"Total Medals Won"</span>)</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">"Country"</span>)</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>ax.legend(loc<span class="op">=</span><span class="st">'lower right'</span>)</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>fig.tight_layout()</span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-alltime" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-alltime-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="blog_files/figure-html/fig-alltime-output-1.png" width="1135" height="846" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-alltime-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Figure 1: Cumulative Winter Olympic medals for the top 20 nations since 1924. Norway’s gold-heavy bar reflects not just volume but consistent dominance across disciplines.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The all-time totals hides a lot of movement, so this chart tracks medals per Games for the top 6 nations.</p>
<div id="cell-fig-overtime" class="cell" data-execution_count="9">
<details class="code-fold">
<summary>Show code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>top6   <span class="op">=</span> cy.groupby(<span class="st">'noc'</span>)[<span class="st">'total_medals'</span>].<span class="bu">sum</span>().nlargest(<span class="dv">6</span>).index.tolist()</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>subset <span class="op">=</span> cy[cy[<span class="st">'noc'</span>].isin(top6)].copy()</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>subset[<span class="st">'country'</span>] <span class="op">=</span> subset[<span class="st">'noc'</span>].<span class="bu">map</span>(NOC_NAMES).fillna(subset[<span class="st">'noc'</span>])</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">11</span>, <span class="dv">6</span>))</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>sns.lineplot(data<span class="op">=</span>subset, x<span class="op">=</span><span class="st">'year'</span>, y<span class="op">=</span><span class="st">'total_medals'</span>, hue<span class="op">=</span><span class="st">'country'</span>, marker<span class="op">=</span><span class="st">'o'</span>, ax<span class="op">=</span>ax)</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">'Winter Olympic Medal Count per Games (Top 6 Nations)'</span>, fontsize<span class="op">=</span><span class="dv">14</span>, pad<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">'Year'</span>, fontsize<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">'Medals Won'</span>, fontsize<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>ax.tick_params(axis<span class="op">=</span><span class="st">'both'</span>, labelsize<span class="op">=</span><span class="dv">10</span>)</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>ax.legend(title<span class="op">=</span><span class="st">'Country'</span>, bbox_to_anchor<span class="op">=</span>(<span class="fl">1.01</span>, <span class="dv">1</span>), loc<span class="op">=</span><span class="st">'upper left'</span>, borderaxespad<span class="op">=</span><span class="fl">0.</span>)</span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a>ax.set_xticks(<span class="bu">sorted</span>(cy[<span class="st">'year'</span>].unique()))</span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a>ax.tick_params(axis<span class="op">=</span><span class="st">'x'</span>, rotation<span class="op">=</span><span class="dv">45</span>)</span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a>fig.tight_layout()</span>
<span id="cb14-18"><a href="#cb14-18" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-overtime" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-overtime-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="blog_files/figure-html/fig-overtime-output-1.png" width="1037" height="556" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-overtime-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Figure 2: Medals won per Games for the top 6 nations by all-time count. The gap between 1936 and 1948 reflects the cancellation of the 1940 and 1944 Games due to World War II. You’ll also notice a clear spike for the United States in 2002, which lines up with the Salt Lake City Games being held on home soil.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Norway is consistently near the top throughout, with very few poor Games. Russia (URS before 1992) came on strong from the mid-1950s and dominated throughout the 1980s but then dropped off sharply after the Soviet Union dissolved. The dominance of wealthy nations raises the obvious next question: Is it just money?</p>
<hr>
</section>
<section id="does-money-buy-medals" class="level2">
<h2 class="anchored" data-anchor-id="does-money-buy-medals">4. Does money buy medals?</h2>
<p>The scatter plot below plots log GDP per capita against total medals. The upward trend is clear, wealthier countries tend to invest more in training and facilities and it shows.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Wealth isn’t everything
</div>
</div>
<div class="callout-body-container callout-body">
<p>Qatar and Singapore rank among the world’s wealthiest nations but have never won a Winter Olympic medal, so climate and sporting culture clearly matter alongside money.</p>
</div>
</div>
<div id="cell-fig-wealth" class="cell" data-execution_count="10">
<details class="code-fold">
<summary>Show code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>plot_data <span class="op">=</span> cy.dropna(subset<span class="op">=</span>[<span class="st">'log_gdp_per_capita'</span>, <span class="st">'total_medals'</span>])</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">6</span>))</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>sns.regplot(data<span class="op">=</span>plot_data, x<span class="op">=</span><span class="st">'log_gdp_per_capita'</span>, y<span class="op">=</span><span class="st">'total_medals'</span>,</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>            scatter_kws<span class="op">=</span>{<span class="st">'alpha'</span>: <span class="fl">0.4</span>, <span class="st">'s'</span>: <span class="dv">25</span>, <span class="st">'color'</span>: BLUE},</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>            line_kws<span class="op">=</span>{<span class="st">'color'</span>: <span class="st">'red'</span>}, ax<span class="op">=</span>ax)</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"Wealthier Countries Win More Medals"</span>, fontsize<span class="op">=</span><span class="dv">14</span>, pad<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"Log GDP per Capita (current USD)"</span>)</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">"Total Medals Won"</span>)</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>fig.tight_layout()</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-wealth" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-wealth-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="blog_files/figure-html/fig-wealth-output-1.png" width="943" height="558" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-wealth-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Figure 3: Relationship between log GDP per capita and total medals won across all country-year observations. The overall upward trend makes it clear that richer countries tend to win more medals. That said, the spread of points around the line is a reminder that wealth isn’t the whole story, other factors still matter.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Wealth clearly plays a role but there is one advantage no investment can buy and that is competing on home soil.</p>
<hr>
</section>
<section id="the-home-advantage" class="level2">
<h2 class="anchored" data-anchor-id="the-home-advantage">5. The home advantage</h2>
<p>To look at home advantage more directly, I compared each host nations medal count in the year they hosted against their average in all other Games, keeping the 15 nations that won the most medals whilst hosting.</p>
<div id="cell-fig-host" class="cell" data-execution_count="11">
<details class="code-fold">
<summary>Show code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>hosts <span class="op">=</span> (cy[cy[<span class="st">'is_host'</span>] <span class="op">==</span> <span class="dv">1</span>][[<span class="st">'noc'</span>, <span class="st">'year'</span>, <span class="st">'total_medals'</span>]].rename(columns<span class="op">=</span>{<span class="st">'total_medals'</span>: <span class="st">'host_medals'</span>}))</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>non_host_avg <span class="op">=</span> (cy[cy[<span class="st">'is_host'</span>] <span class="op">==</span> <span class="dv">0</span>].groupby(<span class="st">'noc'</span>)[<span class="st">'total_medals'</span>].mean().reset_index().rename(columns<span class="op">=</span>{<span class="st">'total_medals'</span>: <span class="st">'avg_non_host'</span>}))</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>compare <span class="op">=</span> (pd.merge(hosts, non_host_avg, on<span class="op">=</span><span class="st">'noc'</span>, how<span class="op">=</span><span class="st">'inner'</span>).sort_values(<span class="st">'host_medals'</span>, ascending<span class="op">=</span><span class="va">False</span>).head(<span class="dv">15</span>))</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="bu">long</span> <span class="op">=</span> compare.melt(id_vars<span class="op">=</span>[<span class="st">'noc'</span>],value_vars<span class="op">=</span>[<span class="st">'host_medals'</span>, <span class="st">'avg_non_host'</span>], var_name<span class="op">=</span><span class="st">'type'</span>, value_name<span class="op">=</span><span class="st">'medals'</span>)</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="bu">long</span>[<span class="st">'type'</span>] <span class="op">=</span> <span class="bu">long</span>[<span class="st">'type'</span>].<span class="bu">map</span>({<span class="st">'host_medals'</span>:  <span class="st">'Host Year'</span>,<span class="st">'avg_non_host'</span>: <span class="st">'Average Non-Host Year'</span>})</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a><span class="bu">long</span>[<span class="st">'country'</span>] <span class="op">=</span> <span class="bu">long</span>[<span class="st">'noc'</span>].<span class="bu">map</span>(NOC_NAMES).fillna(<span class="bu">long</span>[<span class="st">'noc'</span>])</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="dv">7</span>))</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>sns.barplot(data<span class="op">=</span><span class="bu">long</span>, x<span class="op">=</span><span class="st">'country'</span>, y<span class="op">=</span><span class="st">'medals'</span>, hue<span class="op">=</span><span class="st">'type'</span>, ax<span class="op">=</span>ax)</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">'Medals when Hosting vs Not Hosting (Top 15 Host Nations)'</span>,fontsize<span class="op">=</span><span class="dv">14</span>, pad<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">'Country'</span>)</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">'Total Medals'</span>)</span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>ax.tick_params(axis<span class="op">=</span><span class="st">'x'</span>, rotation<span class="op">=</span><span class="dv">45</span>)</span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>fig.tight_layout()</span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-host" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-host-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="blog_files/figure-html/fig-host-output-1.png" width="1135" height="654" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-host-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Figure 4: Medal counts in host years versus average non-host performance for the 15 most successful host nations. Most sit noticeably higher in their host year, for example the USA in 2002 (34 medals) and Norway in 1994 (26 medals).
</figcaption>
</figure>
</div>
</div>
</div>
<p>One thing to note is the chart orders by how many medals they won while hosting not by the size of the boost, so the nations on the left aren’t necessarily the ones who benefitted most.</p>
<p>Home advantage is a one time boost. It cannot explain the collapse of nations like the Soviet Union and East Germany, for that political and historical context matters.</p>
<hr>
</section>
<section id="the-fallen-powers" class="level2">
<h2 class="anchored" data-anchor-id="the-fallen-powers">6. The fallen powers</h2>
<p>Not every nation that dominated the early era has kept that up. The chart compares the average medals per Games for the top 10 early-era nations looking at results up to and including the 1980 verus their average since 1994. Countries are sorted left to right by the size of their drop off.</p>
<div id="cell-fig-fallen" class="cell" data-execution_count="12">
<details class="code-fold">
<summary>Show code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>cy_all <span class="op">=</span> final.groupby([<span class="st">'year'</span>, <span class="st">'noc'</span>], as_index<span class="op">=</span><span class="va">False</span>).agg(total_medals<span class="op">=</span>(<span class="st">'noc'</span>, <span class="st">'count'</span>))</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>early <span class="op">=</span> cy_all[cy_all[<span class="st">'year'</span>] <span class="op">&lt;=</span> <span class="dv">1980</span>]</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>modern <span class="op">=</span> cy_all[cy_all[<span class="st">'year'</span>] <span class="op">&gt;=</span> <span class="dv">1994</span>]</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>early_avg <span class="op">=</span> early.groupby(<span class="st">'noc'</span>)[<span class="st">'total_medals'</span>].mean().rename(<span class="st">'early_avg'</span>).reset_index()</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>modern_avg <span class="op">=</span> modern.groupby(<span class="st">'noc'</span>)[<span class="st">'total_medals'</span>].mean().rename(<span class="st">'modern_avg'</span>).reset_index()</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>top_early <span class="op">=</span> early_avg.nlargest(<span class="dv">10</span>, <span class="st">'early_avg'</span>)[<span class="st">'noc'</span>]</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>compare <span class="op">=</span> pd.merge(early_avg[early_avg[<span class="st">'noc'</span>].isin(top_early)], modern_avg, on<span class="op">=</span><span class="st">'noc'</span>, how<span class="op">=</span><span class="st">'left'</span>).fillna(<span class="dv">0</span>)</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>compare[<span class="st">'decline'</span>] <span class="op">=</span> compare[<span class="st">'early_avg'</span>] <span class="op">-</span> compare[<span class="st">'modern_avg'</span>]</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>compare <span class="op">=</span> compare.sort_values(<span class="st">'decline'</span>, ascending<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a><span class="bu">long</span> <span class="op">=</span> compare.melt(id_vars<span class="op">=</span>[<span class="st">'noc'</span>], value_vars<span class="op">=</span>[<span class="st">'early_avg'</span>, <span class="st">'modern_avg'</span>], var_name<span class="op">=</span><span class="st">'era'</span>, value_name<span class="op">=</span><span class="st">'avg_medals'</span>)</span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a><span class="bu">long</span>[<span class="st">'era'</span>] <span class="op">=</span> <span class="bu">long</span>[<span class="st">'era'</span>].<span class="bu">map</span>({<span class="st">'early_avg'</span>: <span class="st">'Pre-1980 average'</span>, <span class="st">'modern_avg'</span>: <span class="st">'Post-1992 average'</span>})</span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a><span class="bu">long</span>[<span class="st">'country'</span>] <span class="op">=</span> <span class="bu">long</span>[<span class="st">'noc'</span>].<span class="bu">map</span>(NOC_NAMES).fillna(<span class="bu">long</span>[<span class="st">'noc'</span>])</span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="dv">6</span>))</span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a>sns.barplot(data<span class="op">=</span><span class="bu">long</span>, x<span class="op">=</span><span class="st">'country'</span>, y<span class="op">=</span><span class="st">'avg_medals'</span>, hue<span class="op">=</span><span class="st">'era'</span>, ax<span class="op">=</span>ax)</span>
<span id="cb17-19"><a href="#cb17-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-20"><a href="#cb17-20" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">'Early Dominance vs Modern Performance</span><span class="ch">\n</span><span class="st">(Top 10 Pre-1980 Nations)'</span>, fontsize<span class="op">=</span><span class="dv">14</span>, pad<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb17-21"><a href="#cb17-21" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">'Country'</span>)</span>
<span id="cb17-22"><a href="#cb17-22" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">'Average Medals per Games'</span>)</span>
<span id="cb17-23"><a href="#cb17-23" aria-hidden="true" tabindex="-1"></a>ax.legend(title<span class="op">=</span><span class="st">'Era'</span>)</span>
<span id="cb17-24"><a href="#cb17-24" aria-hidden="true" tabindex="-1"></a>ax.tick_params(axis<span class="op">=</span><span class="st">'x'</span>, rotation<span class="op">=</span><span class="dv">45</span>)</span>
<span id="cb17-25"><a href="#cb17-25" aria-hidden="true" tabindex="-1"></a>fig.tight_layout()</span>
<span id="cb17-26"><a href="#cb17-26" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-fallen" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-fallen-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="blog_files/figure-html/fig-fallen-output-1.png" width="1135" height="557" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-fallen-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Figure 5: Average medals per Games for the top 10 pre-1980 nations, comparing their early era performance against the modern era. The collapse of URS and GDR after the Cold War is the most striking feature.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The Soviet Union and East Germnay show the sharpest drops, likely reflecting the collapse of state-funded sports programmes after the Cold War, which is something a GDP regression cannot capture. Norway and the US have held their ground or improved.</p>
<hr>
</section>
<section id="the-full-picture-regression-results" class="level2">
<h2 class="anchored" data-anchor-id="the-full-picture-regression-results">7. The full picture: regression results</h2>
<section id="the-model" class="level3">
<h3 class="anchored" data-anchor-id="the-model">7.1 The model</h3>
<p>With the data aggregated to country-year level, an OLS regression was run to directly answer the research question: after controlling for GDP per capita and population size, does hosting the Games have a significant impact on medal success? The model is:</p>
<blockquote class="blockquote">
<p><strong>Total Medals = β₀ + β₁(is_host) + β₂(log GDP per capita) + β₃(log population) + ε</strong></p>
</blockquote>
<div id="fd6b6e46" class="cell" data-execution_count="13">
<details class="code-fold">
<summary>Show code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.formula.api <span class="im">as</span> smf</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>reg_data <span class="op">=</span> (pd.read_csv(<span class="st">'../data/clean/medals_country_year.csv'</span>))</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>results_df <span class="op">=</span> (pd.read_csv(<span class="st">'../outputs/regression_results.csv'</span>))</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Rows in regression dataset: </span><span class="sc">{</span><span class="bu">len</span>(reg_data)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Countries represented: </span><span class="sc">{</span>reg_data[<span class="st">'noc'</span>]<span class="sc">.</span>nunique()<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Host-country observations: </span><span class="sc">{</span>reg_data[<span class="st">'is_host'</span>]<span class="sc">.</span><span class="bu">sum</span>()<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>()</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(results_df.to_string(index<span class="op">=</span><span class="va">False</span>))</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> smf.ols(<span class="st">'total_medals ~ is_host + log_gdp_per_capita + log_population'</span>, data<span class="op">=</span>reg_data).fit()</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(model.summary())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Rows in regression dataset: 332
Countries represented: 42
Host-country observations: 16

          variable      Coef.  Std.Err.         t        P&gt;|t|     [0.025     0.975]
         Intercept -40.866057  5.524349 -7.397443 1.171844e-12 -51.733683 -29.998431
           is_host   4.618627  1.889718  2.444083 1.504838e-02   0.901131   8.336123
log_gdp_per_capita   2.663723  0.332520  8.010721 2.011258e-14   2.009583   3.317864
    log_population   1.433589  0.243437  5.888950 9.621035e-09   0.954694   1.912484
                            OLS Regression Results                            
==============================================================================
Dep. Variable:           total_medals   R-squared:                       0.230
Model:                            OLS   Adj. R-squared:                  0.223
Method:                 Least Squares   F-statistic:                     32.65
Date:                Mon, 06 Apr 2026   Prob (F-statistic):           1.72e-18
Time:                        20:27:50   Log-Likelihood:                -1128.8
No. Observations:                 332   AIC:                             2266.
Df Residuals:                     328   BIC:                             2281.
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
======================================================================================
                         coef    std err          t      P&gt;|t|      [0.025      0.975]
--------------------------------------------------------------------------------------
Intercept            -40.8661      5.524     -7.397      0.000     -51.734     -29.998
is_host                4.6186      1.890      2.444      0.015       0.901       8.336
log_gdp_per_capita     2.6637      0.333      8.011      0.000       2.010       3.318
log_population         1.4336      0.243      5.889      0.000       0.955       1.912
==============================================================================
Omnibus:                       48.817   Durbin-Watson:                   0.779
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               66.730
Skew:                           1.003   Prob(JB):                     3.23e-15
Kurtosis:                       3.895   Cond. No.                         269.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.</code></pre>
</div>
</div>
<div class="cell" data-execution_count="14">
<details class="code-fold">
<summary>Show code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>comparison <span class="op">=</span> pd.read_csv(<span class="st">'../outputs/model_comparison.csv'</span>)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>comparison.style.set_caption(<span class="st">'Table 2: Basic OLS vs Country Fixed Effects'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div id="tbl-comparison" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="14">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Table 2: Basic OLS vs country fixed effects with only key coefficients
</figcaption>
<div aria-describedby="tbl-comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="14">
<style type="text/css">
</style>

<div id="T_6f766" class="quarto-float quarto-figure quarto-figure-center anchored" data-quarto-postprocess="true">
<figure class="quarto-float quarto-subfloat-tbl figure">
<figcaption class="quarto-float-caption-top quarto-subfloat-caption quarto-subfloat-tbl" id="T_6f766-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Table 2: Basic OLS vs Country Fixed Effects
</figcaption>
<div aria-describedby="T_6f766-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table id="T_6f766" class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th class="blank level0" data-quarto-table-cell-role="th">&nbsp;</th>
<th id="T_6f766_level0_col0" class="col_heading level0 col0" data-quarto-table-cell-role="th">variable</th>
<th id="T_6f766_level0_col1" class="col_heading level0 col1" data-quarto-table-cell-role="th">OLS_coef</th>
<th id="T_6f766_level0_col2" class="col_heading level0 col2" data-quarto-table-cell-role="th">OLS_pval</th>
<th id="T_6f766_level0_col3" class="col_heading level0 col3" data-quarto-table-cell-role="th">FE_coef</th>
<th id="T_6f766_level0_col4" class="col_heading level0 col4" data-quarto-table-cell-role="th">FE_pval</th>
<th id="T_6f766_level0_col5" class="col_heading level0 col5" data-quarto-table-cell-role="th">OLS_stars</th>
<th id="T_6f766_level0_col6" class="col_heading level0 col6" data-quarto-table-cell-role="th">FE_stars</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th id="T_6f766_level0_row0" class="row_heading level0 row0" data-quarto-table-cell-role="th">0</th>
<td id="T_6f766_row0_col0" class="data row0 col0">is_host</td>
<td id="T_6f766_row0_col1" class="data row0 col1">4.619000</td>
<td id="T_6f766_row0_col2" class="data row0 col2">0.015000</td>
<td id="T_6f766_row0_col3" class="data row0 col3">3.985000</td>
<td id="T_6f766_row0_col4" class="data row0 col4">0.001000</td>
<td id="T_6f766_row0_col5" class="data row0 col5">*</td>
<td id="T_6f766_row0_col6" class="data row0 col6">**</td>
</tr>
<tr class="even">
<th id="T_6f766_level0_row1" class="row_heading level0 row1" data-quarto-table-cell-role="th">1</th>
<td id="T_6f766_row1_col0" class="data row1 col0">log_gdp_per_capita</td>
<td id="T_6f766_row1_col1" class="data row1 col1">2.664000</td>
<td id="T_6f766_row1_col2" class="data row1 col2">0.000000</td>
<td id="T_6f766_row1_col3" class="data row1 col3">1.015000</td>
<td id="T_6f766_row1_col4" class="data row1 col4">0.007000</td>
<td id="T_6f766_row1_col5" class="data row1 col5">***</td>
<td id="T_6f766_row1_col6" class="data row1 col6">**</td>
</tr>
<tr class="odd">
<th id="T_6f766_level0_row2" class="row_heading level0 row2" data-quarto-table-cell-role="th">2</th>
<td id="T_6f766_row2_col0" class="data row2 col0">log_population</td>
<td id="T_6f766_row2_col1" class="data row2 col1">1.434000</td>
<td id="T_6f766_row2_col2" class="data row2 col2">0.000000</td>
<td id="T_6f766_row2_col3" class="data row2 col3">26.724000</td>
<td id="T_6f766_row2_col4" class="data row2 col4">0.000000</td>
<td id="T_6f766_row2_col5" class="data row2 col5">***</td>
<td id="T_6f766_row2_col6" class="data row2 col6">***</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</div>
</div>
</figure>
</div>
</div>
<p>The basic OLS shows the raw associations between each predictor and medal counts. The fixed effects version asks a harder question, not “whether host countries win more overall” but “whether a country wins more than it normally would when hosting”.</p>
<p>The <code>is_host</code> coefficient drops from 4.6 in the basic OLS to 4.0 in the fixed effects model, a small decrease, but importantly it remains positive and significant ( p = 0.001, stronger than the basic OLS p = 0.015). Strong countries tend to host, so you would expect them to do well regardless, but the advantage survives even when comparing a country against its own baseline.</p>
<p>The <code>log_gdp_per_capita</code> coefficient drops, from 2.664 to 1.015, which makes sense as once I control for country-specific differences, a lot of the gap in wealth between countries is already absorbed. The <code>log_population</code> coefficient in the fixed effects model is unusually large and should be interpreted with caution, as population doesn’t change much within a country over time, so the model doesn’t have much variation to work with. The basic OLS estimate of 1.434 is the more reliable figure for population in this case.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>What fixed effects adds
</div>
</div>
<div class="callout-body-container callout-body">
<p>The basic OLS <code>is_host</code> coefficient of 4.6 compares the host country-years against all other country-years. Whereas the fixed effects estimate of 4.0 ( p = 0.001) compares a country against its own historical performance, which is a stricter test that hosting effect passes.</p>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Hosting advantage is real
</div>
</div>
<div class="callout-body-container callout-body">
<p>The basic OLS model estimates that host nations win on average <strong>4.6 more medals</strong> than expected after controlling for wealth and population(p = 0.015). The country fixed effects model puts this at <strong>4.0 extra medals</strong> ( p = 0.001), which is a smaller but more credible estimate, as it compares each nation against its own baseline rather than against all other countries.</p>
</div>
</div>
</section>
<section id="what-the-coefficients-show" class="level3">
<h3 class="anchored" data-anchor-id="what-the-coefficients-show">7.2 What the coefficients show</h3>
<p>The coefficient plot below pulls together all three results in one view. All three bars fall to the right of zero, meaning hosting, wealth and population all increase expected medal counts. The host status bar looks the longest, but section 8 explains why that is slightly misleading.</p>
<div id="cell-fig-regression" class="cell" data-execution_count="15">
<details class="code-fold">
<summary>Show code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>key_vars <span class="op">=</span> [<span class="st">'is_host'</span>, <span class="st">'log_gdp_per_capita'</span>, <span class="st">'log_population'</span>]</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>reg_plot <span class="op">=</span> reg[reg[<span class="st">'variable'</span>].isin(key_vars)].copy()</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>reg_plot[<span class="st">'variable'</span>] <span class="op">=</span> reg_plot[<span class="st">'variable'</span>].<span class="bu">map</span>({<span class="st">'is_host'</span>: <span class="st">'Host Country'</span>, <span class="st">'log_gdp_per_capita'</span>: <span class="st">'Log GDP per Capita'</span>, <span class="st">'log_population'</span>: <span class="st">'Log Population'</span>})</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">14</span>, <span class="dv">7</span>))</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>ax.barh(reg_plot[<span class="st">'variable'</span>], reg_plot[<span class="st">'Coef.'</span>])</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>ax.errorbar(reg_plot[<span class="st">'Coef.'</span>], reg_plot[<span class="st">'variable'</span>], xerr<span class="op">=</span>[</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>        reg_plot[<span class="st">'Coef.'</span>] <span class="op">-</span> reg_plot[<span class="st">'[0.025'</span>],</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>        reg_plot[<span class="st">'0.975]'</span>] <span class="op">-</span> reg_plot[<span class="st">'Coef.'</span>]],fmt<span class="op">=</span><span class="st">'none'</span>,color<span class="op">=</span><span class="st">'black'</span>,capsize<span class="op">=</span><span class="dv">4</span>)</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>ax.axvline(<span class="dv">0</span>, color<span class="op">=</span><span class="st">'black'</span>, linewidth<span class="op">=</span><span class="fl">0.8</span>)</span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"What Predicts Winter Olympic Success?"</span>, fontsize<span class="op">=</span><span class="dv">14</span>, pad<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"Regression Coefficient (extra medals per unit increase)"</span>)</span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a>fig.tight_layout()</span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-regression" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-regression-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="blog_files/figure-html/fig-regression-output-1.png" width="1325" height="654" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-regression-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: Figure 6: OLS regression coefficients for the three predictors of Winter Olympic medal success. All bars fall to the right of zero, confirming each factor has a positive impact on medal counts. The error bars show the uncertainty around each estimate, and GDP per capita stands out as the most consistent and reliable predictor due to it having the tightest interval.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The black error bars show the 95% confidence intervals. GDP per capita has the tightest interval of the three, indicating it is the most reliably estimated of the three. The host status bar is wider, reflecting the smaller number of hosting observations in the data.</p>
<hr>
</section>
</section>
<section id="conclusions" class="level2">
<h2 class="anchored" data-anchor-id="conclusions">8. Conclusions</h2>
<p>Norway’s GDP per capita is high but not uniquely so. What the regression cannot capture is a century of winter sports culture and the geography that produces competitive athletes across almost every discipline. The model explains the economic and population factors, but Norway’s outlier status sits above them. All three are statistically significant predictors of medal count.</p>
<section id="host-advantage-is-real-but-limited" class="level4">
<h4 class="anchored" data-anchor-id="host-advantage-is-real-but-limited">Host advantage is real but limited</h4>
<p>The OLS model estimates a boost of 4.6 medals (p = 0.015), tightening to 4.0 under fixed effects ( p = 0.001). The fixed effects result is slightly smaller but more credible, it compares each country against its own baseline rather than against all other nations. The boost is real, but since a country only hosts once every few decades, it explains very little of the long-run medal success. The GDP coefficient falls from 2.664 to 1.015 under fixed effects, as between country wealth differences are absorbed by the country dummies. The population coefficient should be treated with caution in the fixed effects model, as population barely changes within a country over time.</p>
</section>
<section id="gdp-per-capita-is-the-strongest-overall-predictor" class="level4">
<h4 class="anchored" data-anchor-id="gdp-per-capita-is-the-strongest-overall-predictor">GDP per capita is the strongest overall predictor</h4>
<p>From the regression, a 1 unit increase in log GDP per capita is associated with about 2.7 extra medals (p &lt; 0.001), adding up to roughly a 16-medal difference across the full range of countries. Despite the host bar looking longest on the coefficient plot, it only represents a one-time jump, whereas GDP applies continuously across every Games, as well as having more than three times the t-statistic (8.01 vs 2.44) confirming it is the more consistent and reliable predictor across the dataset.</p>
</section>
<section id="population-matters-independently-of-wealth" class="level4">
<h4 class="anchored" data-anchor-id="population-matters-independently-of-wealth">Population matters independently of wealth</h4>
<p>Population also plays an important role, even after accounting for wealth. A 1 unit increase in log population leads to about 1.4 additional medals (p &lt; 0.001). Across the full range of countries, this again adds up to roughly a 16 medal difference, which is comparable in scale to the GDP effect.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Bottom line
</div>
</div>
<div class="callout-body-container callout-body">
<p>Three things shape how well a country does at the Winter Olympics: <strong>wealth</strong>, <strong>population</strong>, and whether it is <strong>hosting</strong>. The OLS model estimates a hosting boost of <strong>4.6 medals</strong> tightening to <strong>4.0 medals</strong> under the stricter fixed effects test. GDP per capita has the most reliable and consistent effect across both models. So if you are trying to predict how many medals a country might win, GDP per capita on its own gets you most of the way there.</p>
</div>
</div>
<hr>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>