<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Octavia Steiger">
<meta name="dcterms.date" content="2026-04-04">

<title>Winter Olympics Medal Analysis</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="report_files/libs/clipboard/clipboard.min.js"></script>
<script src="report_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="report_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="report_files/libs/quarto-html/popper.min.js"></script>
<script src="report_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="report_files/libs/quarto-html/anchor.min.js"></script>
<link href="report_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="report_files/libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="report_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="report_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="report_files/libs/bootstrap/bootstrap-8ffd5f67044e5306d9846f29df41dda5.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#research-question" id="toc-research-question" class="nav-link active" data-scroll-target="#research-question">Research Question</a></li>
  <li><a href="#collecting-the-medal-data" id="toc-collecting-the-medal-data" class="nav-link" data-scroll-target="#collecting-the-medal-data">1. Collecting the Medal Data</a></li>
  <li><a href="#cleaning-the-data" id="toc-cleaning-the-data" class="nav-link" data-scroll-target="#cleaning-the-data">2. Cleaning the Data</a>
  <ul class="collapse">
  <li><a href="#sorting-out-the-sport-categories" id="toc-sorting-out-the-sport-categories" class="nav-link" data-scroll-target="#sorting-out-the-sport-categories">2.1 Sorting out the sport categories</a></li>
  <li><a href="#dealing-with-tied-medals" id="toc-dealing-with-tied-medals" class="nav-link" data-scroll-target="#dealing-with-tied-medals">2.2 Dealing with tied medals</a></li>
  </ul></li>
  <li><a href="#adding-economic-context" id="toc-adding-economic-context" class="nav-link" data-scroll-target="#adding-economic-context">3. Adding Economic Context</a>
  <ul class="collapse">
  <li><a href="#why-i-used-the-world-bank-api" id="toc-why-i-used-the-world-bank-api" class="nav-link" data-scroll-target="#why-i-used-the-world-bank-api">3.1 Why I used the World Bank API</a></li>
  <li><a href="#the-noc-to-isc-problem" id="toc-the-noc-to-isc-problem" class="nav-link" data-scroll-target="#the-noc-to-isc-problem">3.2 The NOC to ISC problem</a></li>
  <li><a href="#merging-the-datasets" id="toc-merging-the-datasets" class="nav-link" data-scroll-target="#merging-the-datasets">3.3 Merging the datasets</a></li>
  </ul></li>
  <li><a href="#the-analysis" id="toc-the-analysis" class="nav-link" data-scroll-target="#the-analysis">4. The Analysis</a>
  <ul class="collapse">
  <li><a href="#aggregating-to-country-year-level" id="toc-aggregating-to-country-year-level" class="nav-link" data-scroll-target="#aggregating-to-country-year-level">4.1 Aggregating to country-year level</a></li>
  <li><a href="#ols-regression" id="toc-ols-regression" class="nav-link" data-scroll-target="#ols-regression">4.2 OLS regression</a></li>
  </ul></li>
  <li><a href="#visualising-the-results" id="toc-visualising-the-results" class="nav-link" data-scroll-target="#visualising-the-results">5. Visualising the Results</a>
  <ul class="collapse">
  <li><a href="#all-time-medal-table" id="toc-all-time-medal-table" class="nav-link" data-scroll-target="#all-time-medal-table">5.1 All-time Medal table</a></li>
  <li><a href="#the-fallen-powers" id="toc-the-fallen-powers" class="nav-link" data-scroll-target="#the-fallen-powers">5.2 The Fallen Powers</a></li>
  <li><a href="#how-medal-dominance-has-changed-over-time" id="toc-how-medal-dominance-has-changed-over-time" class="nav-link" data-scroll-target="#how-medal-dominance-has-changed-over-time">5.3 How medal dominance has changed over time</a></li>
  <li><a href="#the-wealth-effects" id="toc-the-wealth-effects" class="nav-link" data-scroll-target="#the-wealth-effects">5.4 The Wealth effects</a></li>
  <li><a href="#home-advantage" id="toc-home-advantage" class="nav-link" data-scroll-target="#home-advantage">5.5 Home Advantage</a></li>
  <li><a href="#what-the-regression-tells-us" id="toc-what-the-regression-tells-us" class="nav-link" data-scroll-target="#what-the-regression-tells-us">5.6 What the regression tells us</a></li>
  </ul></li>
  <li><a href="#conclusions" id="toc-conclusions" class="nav-link" data-scroll-target="#conclusions">6. Conclusions</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Winter Olympics Medal Analysis</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Octavia Steiger </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">April 4, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="research-question" class="level2">
<h2 class="anchored" data-anchor-id="research-question">Research Question</h2>
<p>What actually drives medal succes in the Winter Olympics? Is it just the wealth of a country, ie richer countries have more resources to invest in training and facilities or population size, ie more people means more potential athletes? Or does hosting the Games give a country an advantage?</p>
<p>To answer this, I needed to look at the medal counts over time, the economic data of each country competing and the hosting history of the Winter Olympics. In the sections below I walk through the data pipeline I used to answer this question and the steps I took to get to the final result.</p>
<p>The short answer: yes to all three, but not equally. Wealth and population size are the strongest predictors of medal success, while hosting provides a measurable but smaller boost above and beyond those factors.</p>
<p>The data pipeline: scrape –&gt; clean –&gt; merge with World Bank data –&gt; analyse –&gt; visualise</p>
<hr>
</section>
<section id="collecting-the-medal-data" class="level2">
<h2 class="anchored" data-anchor-id="collecting-the-medal-data">1. Collecting the Medal Data</h2>
<p>The first step was to collect the medal data for each of the Winter Olympic Games all the way back to 1924. Offical Olympic datawas not available as a download, so the data had to be scraped directly from Olmpedia (https://www.olympedia.org).</p>
<p>I built a web scraper (<code>scrape.py</code>) that fetched the medal table for each of the 24 Winter Olympic Games, making sure that I paused between requests to avoid overwhelming the server. Each page returned an HTML table listing every event alongside gold, silver and bronze medalists and their countries.</p>
<p>The raw data came back in a wide format, with seperate columns for gold, silver and bronze medalists. At this point the data was still quite messy, with country names in different formats, sports categories mixed in as heading rows and some NOC fields had combined codes for when medals were tied. This all needed fixing before I could start with any analysis.</p>
<p>The dataset spans 24 Games from Chamonix 1924 to Beijing 2022, covering 1163 unique events. Not all NOCs appear in each Games, the number of competiting nations has grown over time, from around 19 nations in 1924 to over 90 today.</p>
<div id="2f2d79af" class="cell" data-execution_count="1">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>medals <span class="op">=</span> pd.read_csv(<span class="st">'../data/clean/medals_clean.csv'</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="bu">len</span>(medals)<span class="sc">}</span><span class="ss"> events scraped across </span><span class="sc">{</span>medals[<span class="st">'year'</span>]<span class="sc">.</span>nunique()<span class="sc">}</span><span class="ss"> Games"</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>medals.head(<span class="dv">10</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>1163 events scraped across 24 Games</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="1">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">year</th>
<th data-quarto-table-cell-role="th">sport</th>
<th data-quarto-table-cell-role="th">event</th>
<th data-quarto-table-cell-role="th">gold_name</th>
<th data-quarto-table-cell-role="th">gold_noc</th>
<th data-quarto-table-cell-role="th">tie_gold</th>
<th data-quarto-table-cell-role="th">silver_name</th>
<th data-quarto-table-cell-role="th">silver_noc</th>
<th data-quarto-table-cell-role="th">tie_silver</th>
<th data-quarto-table-cell-role="th">bronze_name</th>
<th data-quarto-table-cell-role="th">bronze_noc</th>
<th data-quarto-table-cell-role="th">tie_bronze</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>1924</td>
<td>Alpinism</td>
<td>Alpinism, Open</td>
<td>Mixed team</td>
<td>MIX</td>
<td>False</td>
<td>—</td>
<td>—</td>
<td>False</td>
<td>—</td>
<td>—</td>
<td>False</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>1924</td>
<td>Bobsleigh</td>
<td>Four, Men</td>
<td>Switzerland 1</td>
<td>SUI</td>
<td>False</td>
<td>Great Britain 1</td>
<td>GBR</td>
<td>False</td>
<td>Belgium 1</td>
<td>BEL</td>
<td>False</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>1924</td>
<td>Cross Country Skiing</td>
<td>18 kilometres, Men</td>
<td>Thorleif Haug</td>
<td>NOR</td>
<td>False</td>
<td>Johan Grøttumsbraaten</td>
<td>NOR</td>
<td>False</td>
<td>Tapani Niku</td>
<td>FIN</td>
<td>False</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>1924</td>
<td>Cross Country Skiing</td>
<td>50 kilometres, Men</td>
<td>Thorleif Haug</td>
<td>NOR</td>
<td>False</td>
<td>Thoralf Strømstad</td>
<td>NOR</td>
<td>False</td>
<td>Johan Grøttumsbraaten</td>
<td>NOR</td>
<td>False</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>1924</td>
<td>Curling</td>
<td>Team, Men</td>
<td>Great Britain</td>
<td>GBR</td>
<td>False</td>
<td>Sweden</td>
<td>SWE</td>
<td>False</td>
<td>France</td>
<td>FRA</td>
<td>False</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>1924</td>
<td>Figure Skating</td>
<td>Singles, Men</td>
<td>Gillis Grafström</td>
<td>SWE</td>
<td>False</td>
<td>Willy Böckl</td>
<td>AUT</td>
<td>False</td>
<td>Georges Gautschi</td>
<td>SUI</td>
<td>False</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>1924</td>
<td>Figure Skating</td>
<td>Singles, Women</td>
<td>Herma Planck-Szabo</td>
<td>AUT</td>
<td>False</td>
<td>Beatrix Loughran</td>
<td>USA</td>
<td>False</td>
<td>Ethel Muckelt</td>
<td>GBR</td>
<td>False</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">7</th>
<td>1924</td>
<td>Figure Skating</td>
<td>Pairs, Mixed</td>
<td>Austria</td>
<td>AUT</td>
<td>False</td>
<td>Finland</td>
<td>FIN</td>
<td>False</td>
<td>France 1</td>
<td>FRA</td>
<td>False</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">8</th>
<td>1924</td>
<td>Ice Hockey</td>
<td>Ice Hockey, Men</td>
<td>Canada</td>
<td>CAN</td>
<td>False</td>
<td>United States</td>
<td>USA</td>
<td>False</td>
<td>Great Britain</td>
<td>GBR</td>
<td>False</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">9</th>
<td>1924</td>
<td>Military Ski Patrol</td>
<td>Military Ski Patrol, Men</td>
<td>Switzerland</td>
<td>SUI</td>
<td>False</td>
<td>Finland</td>
<td>FIN</td>
<td>False</td>
<td>France</td>
<td>FRA</td>
<td>False</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<hr>
</section>
<section id="cleaning-the-data" class="level2">
<h2 class="anchored" data-anchor-id="cleaning-the-data">2. Cleaning the Data</h2>
<section id="sorting-out-the-sport-categories" class="level3">
<h3 class="anchored" data-anchor-id="sorting-out-the-sport-categories">2.1 Sorting out the sport categories</h3>
<p>The scraped HTML table included two types of rows: actual event results and section headings that just said the sport name. These headings were not real results, they had no medalists data or NOC codes, however they did have the sport name of each event which is information I still needed.</p>
<p>To fix this, within the cleaning script (<code>clean.py</code>) I identified the heading rows which was any row where all medal columns were empty and then extracted the sport name. Allowing me to forward fill the sport name down to all the event rows below it until reaching the next heading. Then I could drop the original heading rows as they were no longer needed.</p>
<div id="778bea7c" class="cell" data-execution_count="2">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Sports present in the dataset:"</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="bu">sorted</span>(medals[<span class="st">'sport'</span>].dropna().unique().tolist()))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Sports present in the dataset:
['Alpine Skiing', 'Alpinism', 'Biathlon', 'Bobsleigh', 'Cross Country Skiing', 'Curling', 'Figure Skating', 'Freestyle Skiing', 'Ice Hockey', 'Luge', 'Military Ski Patrol', 'Nordic Combined', 'Short Track Speed Skating', 'Skeleton', 'Ski Jumping', 'Snowboarding', 'Speed Skating']</code></pre>
</div>
</div>
</section>
<section id="dealing-with-tied-medals" class="level3">
<h3 class="anchored" data-anchor-id="dealing-with-tied-medals">2.2 Dealing with tied medals</h3>
<p>Occasionally there were two countries that shared a podium position, for example two gold medalists and no silver. In the raw data these appear as a single combined entry in the NOC column rather than as two seperate rows.</p>
<p>These needed to be detected and split into two rows, otherwise any country-level analysis would be inaccurate. Within the cleaning step these are flagged using the <code>tie</code> columns and then are split into seperate rows in a later step in the pipeline, so that both countries get the credit for the medal in the analysis.</p>
<div id="1f5788bd" class="cell" data-execution_count="3">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>tied <span class="op">=</span> medals[medals[<span class="st">'tie_gold'</span>] <span class="op">|</span> medals[<span class="st">'tie_silver'</span>] <span class="op">|</span> medals[<span class="st">'tie_bronze'</span>]]</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Events with at least one tied medal: </span><span class="sc">{</span><span class="bu">len</span>(tied)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>tied[[<span class="st">'year'</span>, <span class="st">'sport'</span>, <span class="st">'event'</span>, <span class="st">'tie_gold'</span>, <span class="st">'tie_silver'</span>, <span class="st">'tie_bronze'</span>]].head(<span class="dv">8</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Events with at least one tied medal: 27</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="3">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">year</th>
<th data-quarto-table-cell-role="th">sport</th>
<th data-quarto-table-cell-role="th">event</th>
<th data-quarto-table-cell-role="th">tie_gold</th>
<th data-quarto-table-cell-role="th">tie_silver</th>
<th data-quarto-table-cell-role="th">tie_bronze</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">12</th>
<td>1924</td>
<td>Speed Skating</td>
<td>500 metres, Men</td>
<td>False</td>
<td>False</td>
<td>True</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">27</th>
<td>1928</td>
<td>Speed Skating</td>
<td>500 metres, Men</td>
<td>True</td>
<td>False</td>
<td>False</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">61</th>
<td>1948</td>
<td>Alpine Skiing</td>
<td>Downhill, Men</td>
<td>False</td>
<td>False</td>
<td>True</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">101</th>
<td>1952</td>
<td>Speed Skating</td>
<td>500 metres, Men</td>
<td>False</td>
<td>False</td>
<td>True</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">126</th>
<td>1956</td>
<td>Speed Skating</td>
<td>1,500 metres, Men</td>
<td>True</td>
<td>False</td>
<td>False</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">149</th>
<td>1960</td>
<td>Speed Skating</td>
<td>1,500 metres, Men</td>
<td>True</td>
<td>False</td>
<td>False</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">160</th>
<td>1964</td>
<td>Alpine Skiing</td>
<td>Giant Slalom, Women</td>
<td>False</td>
<td>True</td>
<td>False</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">174</th>
<td>1964</td>
<td>Figure Skating</td>
<td>Pairs, Mixed</td>
<td>False</td>
<td>True</td>
<td>False</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>There are relatively few tied medals within the data however just ignoring them would mean undercounting the total medals for the countries involved and would lead to skewed results from the analysis.</p>
<hr>
</section>
</section>
<section id="adding-economic-context" class="level2">
<h2 class="anchored" data-anchor-id="adding-economic-context">3. Adding Economic Context</h2>
<p>This is all great, but to answer the research question I also need to add some economic context to the medal data. To test if wealth or population drives success, each medal row needs to be merged with the GDP and population data for the corresponding country and year.</p>
<section id="why-i-used-the-world-bank-api" class="level3">
<h3 class="anchored" data-anchor-id="why-i-used-the-world-bank-api">3.1 Why I used the World Bank API</h3>
<p>I needed two indicators for each country and year: GDP per capita and population size. The World Bank API provided a convinent way to access this data for all the countries and years in my medal dataset. The advantage of using the World Bank for both is that the data is already cleaned and standardised, meaning I didn’t have to worry about different country name formats or different structures for the data.</p>
<p>They were both fetched directly from the World Bank API (https://data.worldbank.org/) using the <code>wbgapi</code> Python package, allowing for easy integration into the data pipeline.</p>
</section>
<section id="the-noc-to-isc-problem" class="level3">
<h3 class="anchored" data-anchor-id="the-noc-to-isc-problem">3.2 The NOC to ISC problem</h3>
<p>There was however a problem with merging the medal data with the World Bank data, as the medal data uses NOC codes to identify countries, whereas the World Bank data uses ISO country codes. This meant that I needed to find a way to map between the two code systems in order to merge the datasets together as well as the problem of some NOCs no longer existing or being split into multiple countries over time. So I had to create a lookup table to map each NOC to its cloests modern equivalent, so that historical medals can still be joined to economic data where possible.</p>
<p>The trickest cases were the Soviet Union (URS), East Germany (GDR) and Yugoslavia (YUG) which are all heavy medal winners that no longer exists. For these I mapped to their largest successor state (Russia, Germany and Serbia) where economic data was available and excluded rows where I could not make a reasonable match.</p>
</section>
<section id="merging-the-datasets" class="level3">
<h3 class="anchored" data-anchor-id="merging-the-datasets">3.3 Merging the datasets</h3>
<p>Once both datasets used the same country codes, they were joined on country and year. This allowed me to have a single dataset that included the medal information alongside the economic indicators for each country and year which I could then use for analysis. Alongside this I created two additional columns:</p>
<ul>
<li><strong><code>is_host</code></strong> : a flag marking whether the winning country was hosting the games that year, to test the impact of home advantage</li>
<li><strong><code>log_gdp_per_capita</code></strong> and <strong><code>log_population</code></strong>: I took the log of both GDP per Capita and population to make the data more normally distributed, as the difference between a very poor and a moderately poor country is much more significant than the difference between a moderately rich and a very rich country, so taking the log allows for a more meaningful analysis of the relationship between wealth and medal success.</li>
</ul>
<div id="b7925cf7" class="cell" data-execution_count="4">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>final <span class="op">=</span> pd.read_csv(<span class="st">"../data/clean/worldbank_final.csv"</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Final merged dataset: </span><span class="sc">{</span><span class="bu">len</span>(final)<span class="sc">}</span><span class="ss"> medal rows"</span>)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>final.head(<span class="dv">8</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Final merged dataset: 3493 medal rows</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="4">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">year</th>
<th data-quarto-table-cell-role="th">event</th>
<th data-quarto-table-cell-role="th">noc</th>
<th data-quarto-table-cell-role="th">medal</th>
<th data-quarto-table-cell-role="th">iso_code</th>
<th data-quarto-table-cell-role="th">gdp_per_capita</th>
<th data-quarto-table-cell-role="th">population</th>
<th data-quarto-table-cell-role="th">host_noc</th>
<th data-quarto-table-cell-role="th">is_host</th>
<th data-quarto-table-cell-role="th">log_gdp_per_capita</th>
<th data-quarto-table-cell-role="th">log_population</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>1924</td>
<td>Singles, Women</td>
<td>AUT</td>
<td>gold</td>
<td>AUT</td>
<td>NaN</td>
<td>NaN</td>
<td>FRA</td>
<td>0</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>1924</td>
<td>Pairs, Mixed</td>
<td>AUT</td>
<td>gold</td>
<td>AUT</td>
<td>NaN</td>
<td>NaN</td>
<td>FRA</td>
<td>0</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>1924</td>
<td>Singles, Men</td>
<td>AUT</td>
<td>silver</td>
<td>AUT</td>
<td>NaN</td>
<td>NaN</td>
<td>FRA</td>
<td>0</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>1924</td>
<td>Four, Men</td>
<td>BEL</td>
<td>bronze</td>
<td>BEL</td>
<td>NaN</td>
<td>NaN</td>
<td>FRA</td>
<td>0</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>1924</td>
<td>Ice Hockey, Men</td>
<td>CAN</td>
<td>gold</td>
<td>CAN</td>
<td>NaN</td>
<td>NaN</td>
<td>FRA</td>
<td>0</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>1924</td>
<td>18 kilometres, Men</td>
<td>FIN</td>
<td>bronze</td>
<td>FIN</td>
<td>NaN</td>
<td>NaN</td>
<td>FRA</td>
<td>0</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>1924</td>
<td>Allround, Men</td>
<td>FIN</td>
<td>bronze</td>
<td>FIN</td>
<td>NaN</td>
<td>NaN</td>
<td>FRA</td>
<td>0</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">7</th>
<td>1924</td>
<td>500 metres, Men</td>
<td>FIN</td>
<td>bronze</td>
<td>FIN</td>
<td>NaN</td>
<td>NaN</td>
<td>FRA</td>
<td>0</td>
<td>NaN</td>
<td>NaN</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="032efc7e" class="cell" data-execution_count="5">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>missing <span class="op">=</span> final[<span class="st">'gdp_per_capita'</span>].isna().<span class="bu">sum</span>()</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>total <span class="op">=</span> <span class="bu">len</span>(final)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Rows with missing GDP per capita: </span><span class="sc">{</span>missing<span class="sc">}</span><span class="ss"> (</span><span class="sc">{</span><span class="dv">100</span> <span class="op">*</span> missing <span class="op">/</span> total<span class="sc">:.1f}</span><span class="ss">%)'</span>)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'These are mostly historic NOCs'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Rows with missing GDP per capita: 567 (16.2%)
These are mostly historic NOCs</code></pre>
</div>
</div>
<p>The missing GDP rows are expected and unavoidable, as many of the older NOCs no longer exist and therefore do not have corresponding economic data in the World Bank dataset. Therefore, these rows are excluded from the regression but kept in the raw medal count so the all-time table remains accurate.</p>
<hr>
</section>
</section>
<section id="the-analysis" class="level2">
<h2 class="anchored" data-anchor-id="the-analysis">4. The Analysis</h2>
<section id="aggregating-to-country-year-level" class="level3">
<h3 class="anchored" data-anchor-id="aggregating-to-country-year-level">4.1 Aggregating to country-year level</h3>
<p>The merged dataset currently has one row per medal won by a country. However for the regression analysis I need to have one row per country per Olympic year. So that for each country-year combination I have the total number of medals won and I keep the GDP per capita and population data for that country and year.</p>
</section>
<section id="ols-regression" class="level3">
<h3 class="anchored" data-anchor-id="ols-regression">4.2 OLS regression</h3>
<p>With the data in this shape, an OLS regression was run to directly answer the research question: after controlling for GDP per capita and population size, does hosting the games have a significant impact on medal success? The model is: &gt;<strong>Total Medals = beta0 + beta1(is_host) + beta2(log GDP per capita) + beta3(log population) + epsilon</strong></p>
<div id="8ef627c6" class="cell" data-execution_count="6">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.formula.api <span class="im">as</span> smf</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>reg_data <span class="op">=</span> (pd.read_csv(<span class="st">'../data/clean/medals_country_year.csv'</span>))</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>results_df <span class="op">=</span> (pd.read_csv(<span class="st">'../outputs/regression_results.csv'</span>))</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Rows in regression dataset: </span><span class="sc">{</span><span class="bu">len</span>(reg_data)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Countries represented: </span><span class="sc">{</span>reg_data[<span class="st">'noc'</span>]<span class="sc">.</span>nunique()<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Host-country observations: </span><span class="sc">{</span>reg_data[<span class="st">'is_host'</span>]<span class="sc">.</span><span class="bu">sum</span>()<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>()</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(results_df.to_string(index<span class="op">=</span><span class="va">False</span>))</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> smf.ols(<span class="st">'total_medals ~ is_host + log_gdp_per_capita + log_population'</span>, data<span class="op">=</span>reg_data).fit()</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(model.summary())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Rows in regression dataset: 332
Countries represented: 42
Host-country observations: 16

          variable      Coef.  Std.Err.         t        P&gt;|t|     [0.025     0.975]
         Intercept -40.866057  5.524349 -7.397443 1.171844e-12 -51.733683 -29.998431
           is_host   4.618627  1.889718  2.444083 1.504838e-02   0.901131   8.336123
log_gdp_per_capita   2.663723  0.332520  8.010721 2.011258e-14   2.009583   3.317864
    log_population   1.433589  0.243437  5.888950 9.621035e-09   0.954694   1.912484
                            OLS Regression Results                            
==============================================================================
Dep. Variable:           total_medals   R-squared:                       0.230
Model:                            OLS   Adj. R-squared:                  0.223
Method:                 Least Squares   F-statistic:                     32.65
Date:                Sat, 04 Apr 2026   Prob (F-statistic):           1.72e-18
Time:                        14:59:03   Log-Likelihood:                -1128.8
No. Observations:                 332   AIC:                             2266.
Df Residuals:                     328   BIC:                             2281.
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
======================================================================================
                         coef    std err          t      P&gt;|t|      [0.025      0.975]
--------------------------------------------------------------------------------------
Intercept            -40.8661      5.524     -7.397      0.000     -51.734     -29.998
is_host                4.6186      1.890      2.444      0.015       0.901       8.336
log_gdp_per_capita     2.6637      0.333      8.011      0.000       2.010       3.318
log_population         1.4336      0.243      5.889      0.000       0.955       1.912
==============================================================================
Omnibus:                       48.817   Durbin-Watson:                   0.779
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               66.730
Skew:                           1.003   Prob(JB):                     3.23e-15
Kurtosis:                       3.895   Cond. No.                         269.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.</code></pre>
</div>
</div>
<p>The key result, is_host, has a coefficient of approximately 4.6, meaning a host nation wins around 4.6 more medals than it otherwise would, holding GDP and population constant. Both log_gdp_per_capita and log_population are highly significant (p &lt; 0.001), confirming that wealth and size independently drive performance.</p>
</section>
</section>
<section id="visualising-the-results" class="level2">
<h2 class="anchored" data-anchor-id="visualising-the-results">5. Visualising the Results</h2>
<div id="9d7a6c7b" class="cell" data-execution_count="7">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>sns.set_theme(style<span class="op">=</span><span class="st">'whitegrid'</span>, font_scale<span class="op">=</span><span class="fl">1.1</span>)</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>GOLD   <span class="op">=</span> <span class="st">"#FFD700"</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>SILVER <span class="op">=</span> <span class="st">"#C0C0C0"</span></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>BRONZE <span class="op">=</span> <span class="st">"#CD7F32"</span></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>BLUE   <span class="op">=</span> <span class="st">"#1f77b4"</span></span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>alltime <span class="op">=</span> pd.read_csv(<span class="st">"../data/clean/alltime_table.csv"</span>)</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>cy      <span class="op">=</span> pd.read_csv(<span class="st">"../data/clean/medals_country_year.csv"</span>)</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>reg     <span class="op">=</span> pd.read_csv(<span class="st">"../outputs/regression_results.csv"</span>)</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>final   <span class="op">=</span> pd.read_csv(<span class="st">"../data/clean/worldbank_final.csv"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<section id="all-time-medal-table" class="level3">
<h3 class="anchored" data-anchor-id="all-time-medal-table">5.1 All-time Medal table</h3>
<p>The chart shows cumulative medals since 1924 across the top 20 nations. Norway leads comfortably, which makes sense given how deeply embedded winter sport is in Norwegain culture, skiing is almost a national pastime. What’s also interesting is how much of Norway’s bar is gold rather than silver or bronze, showing it doesnt just compete by consistently wins. The US and Germany follow, both benefitting from their size and long-term investment in winter sport. Looking at the stacked bars, some countries accumulate big totals but through silver and bronze rather than gold, which tells a slightly different story about dominance vs participation.</p>
<div id="a95ba4f5" class="cell" data-execution_count="8">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">7</span>, <span class="dv">5</span>))</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>ax.barh(alltime[<span class="st">'noc'</span>], alltime[<span class="st">'gold_medals'</span>], label<span class="op">=</span><span class="st">'Gold'</span>, color<span class="op">=</span>GOLD, height<span class="op">=</span><span class="fl">0.6</span>)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>ax.barh(alltime[<span class="st">'noc'</span>], alltime[<span class="st">'silver_medals'</span>], label<span class="op">=</span><span class="st">'Silver'</span>, color<span class="op">=</span>SILVER, height<span class="op">=</span><span class="fl">0.6</span>, left<span class="op">=</span>alltime[<span class="st">'gold_medals'</span>])</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>ax.barh(alltime[<span class="st">'noc'</span>], alltime[<span class="st">'bronze_medals'</span>], label<span class="op">=</span><span class="st">'Bronze'</span>, color<span class="op">=</span>BRONZE, height<span class="op">=</span><span class="fl">0.6</span>, left<span class="op">=</span>alltime[<span class="st">'gold_medals'</span>] <span class="op">+</span> alltime[<span class="st">'silver_medals'</span>])</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>ax.invert_yaxis()</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"All time Winter Olympics Medal Table (top 20)"</span>, fontsize<span class="op">=</span><span class="dv">14</span>, pad<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"Total Medals Won"</span>)</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">"Country"</span>)</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>ax.legend(loc<span class="op">=</span><span class="st">'lower right'</span>)</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>fig.tight_layout()</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/cell-9-output-1.png" width="655" height="462" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="the-fallen-powers" class="level3">
<h3 class="anchored" data-anchor-id="the-fallen-powers">5.2 The Fallen Powers</h3>
<p>Not every nation that dominated the early era has kept that up. The chart compares the average medals per Games for the top 10 early-era nations looking at results up to and including the 1980 verus their average since 1994. Countries are sorted left to right by the size of their drop off. The biggest declines are URS (The Soviet Union) and GDR (East Germany), which may have been as a result of political and economic disruptions following the Cold War which had lasting impacts on state funded sports programmes. Norway and the US on the other hand have held their ground or improved, which probably comes down to continued investment in winter sport at a national level.</p>
<div id="2dfb2d56" class="cell" data-execution_count="9">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>cy_all <span class="op">=</span> final.groupby([<span class="st">'year'</span>, <span class="st">'noc'</span>], as_index<span class="op">=</span><span class="va">False</span>).agg(total_medals<span class="op">=</span>(<span class="st">'noc'</span>, <span class="st">'count'</span>))</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>early <span class="op">=</span> cy_all[cy_all[<span class="st">'year'</span>] <span class="op">&lt;=</span> <span class="dv">1980</span>]</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>modern <span class="op">=</span> cy_all[cy_all[<span class="st">'year'</span>] <span class="op">&gt;=</span> <span class="dv">1994</span>]</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>early_avg <span class="op">=</span> early.groupby(<span class="st">'noc'</span>)[<span class="st">'total_medals'</span>].mean().rename(<span class="st">'early_avg'</span>).reset_index()</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>modern_avg <span class="op">=</span> modern.groupby(<span class="st">'noc'</span>)[<span class="st">'total_medals'</span>].mean().rename(<span class="st">'modern_avg'</span>).reset_index()</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>top_early <span class="op">=</span> early_avg.nlargest(<span class="dv">10</span>, <span class="st">'early_avg'</span>)[<span class="st">'noc'</span>]</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>compare <span class="op">=</span> pd.merge(early_avg[early_avg[<span class="st">'noc'</span>].isin(top_early)], modern_avg, on<span class="op">=</span><span class="st">'noc'</span>, how<span class="op">=</span><span class="st">'left'</span>).fillna(<span class="dv">0</span>)</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>compare[<span class="st">'decline'</span>] <span class="op">=</span> compare[<span class="st">'early_avg'</span>] <span class="op">-</span> compare[<span class="st">'modern_avg'</span>]</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>compare <span class="op">=</span> compare.sort_values(<span class="st">'decline'</span>, ascending<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a><span class="bu">long</span> <span class="op">=</span> compare.melt(id_vars<span class="op">=</span>[<span class="st">'noc'</span>], value_vars<span class="op">=</span>[<span class="st">'early_avg'</span>, <span class="st">'modern_avg'</span>], var_name<span class="op">=</span><span class="st">'era'</span>, value_name<span class="op">=</span><span class="st">'avg_medals'</span>)</span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a><span class="bu">long</span>[<span class="st">'era'</span>] <span class="op">=</span> <span class="bu">long</span>[<span class="st">'era'</span>].<span class="bu">map</span>({<span class="st">'early_avg'</span>: <span class="st">'Pre-1980 average'</span>, <span class="st">'modern_avg'</span>: <span class="st">'Post-1992 average'</span>})</span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">7</span>, <span class="dv">4</span>))</span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a>sns.barplot(data<span class="op">=</span><span class="bu">long</span>, x<span class="op">=</span><span class="st">'noc'</span>, y<span class="op">=</span><span class="st">'avg_medals'</span>, hue<span class="op">=</span><span class="st">'era'</span>, ax<span class="op">=</span>ax)</span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">'Early Dominance vs Modern Performance</span><span class="ch">\n</span><span class="st">(Top 10 Pre-1980 Nations)'</span>, fontsize<span class="op">=</span><span class="dv">14</span>, pad<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">'Country'</span>)</span>
<span id="cb15-20"><a href="#cb15-20" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">'Average Medals per Games'</span>)</span>
<span id="cb15-21"><a href="#cb15-21" aria-hidden="true" tabindex="-1"></a>ax.legend(title<span class="op">=</span><span class="st">'Era'</span>)</span>
<span id="cb15-22"><a href="#cb15-22" aria-hidden="true" tabindex="-1"></a>ax.tick_params(axis<span class="op">=</span><span class="st">'x'</span>, rotation<span class="op">=</span><span class="dv">45</span>)</span>
<span id="cb15-23"><a href="#cb15-23" aria-hidden="true" tabindex="-1"></a>fig.tight_layout()</span>
<span id="cb15-24"><a href="#cb15-24" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/cell-10-output-1.png" width="655" height="365" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="how-medal-dominance-has-changed-over-time" class="level3">
<h3 class="anchored" data-anchor-id="how-medal-dominance-has-changed-over-time">5.3 How medal dominance has changed over time</h3>
<p>The all-time totals hide a lot of movement at the Games level, so this chart tracks medals per Games for the top 6 nations by all-time count. A few things stand out, Norway is consistently near the top throughout, with very few poor Games. Russia (URS before 1992) came on strong from the mid-1950s and dominated throught the 1980s but then dropped off sharply after the Soviet Union dissolved. You can also see a clear spike for the US in 2002, when they were hosting the Salt Lake City Games, which provides a nice visual of the home advantage effect. The gap between 1936 and 1948 is where thr 1940 and 1944 Games would have been but they were both cancelled because of World War II.</p>
<div id="fa3f2d10" class="cell" data-execution_count="10">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>top6   <span class="op">=</span> cy.groupby(<span class="st">'noc'</span>)[<span class="st">'total_medals'</span>].<span class="bu">sum</span>().nlargest(<span class="dv">6</span>).index.tolist()</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>subset <span class="op">=</span> cy[cy[<span class="st">'noc'</span>].isin(top6)]</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">7</span>, <span class="dv">4</span>))</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>sns.lineplot(data<span class="op">=</span>subset, x<span class="op">=</span><span class="st">'year'</span>, y<span class="op">=</span><span class="st">'total_medals'</span>,</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>             hue<span class="op">=</span><span class="st">'noc'</span>, marker<span class="op">=</span><span class="st">'o'</span>, ax<span class="op">=</span>ax)</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">'Winter Olympic Medal Count per Games (Top 6 Nations)'</span>,</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>             fontsize<span class="op">=</span><span class="dv">14</span>, pad<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">'Year'</span>)</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">'Medals Won'</span>)</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>ax.legend(title<span class="op">=</span><span class="st">'Country'</span>, bbox_to_anchor<span class="op">=</span>(<span class="fl">1.01</span>, <span class="dv">1</span>),</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>          loc<span class="op">=</span><span class="st">'upper left'</span>, borderaxespad<span class="op">=</span><span class="fl">0.</span>)</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>ax.set_xticks(<span class="bu">sorted</span>(cy[<span class="st">'year'</span>].unique()))</span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>ax.tick_params(axis<span class="op">=</span><span class="st">'x'</span>, rotation<span class="op">=</span><span class="dv">45</span>)</span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>fig.tight_layout()</span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/cell-11-output-1.png" width="654" height="366" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="the-wealth-effects" class="level3">
<h3 class="anchored" data-anchor-id="the-wealth-effects">5.4 The Wealth effects</h3>
<p>The scatter plot shows the relationship between GDP per capita and total medals won, across all country-year observations. The upward trend is clear, wealthier countries tend to win more medals, consistent with the idea that richer nations ahve more resources to invest in training, facilities and athlete development. However, there are notable outliers in both directions, some high income nations with no winter sports traditions win very few medals despite their wealth.</p>
<div id="87726f57" class="cell" data-execution_count="11">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>plot_data <span class="op">=</span> cy.dropna(subset<span class="op">=</span>[<span class="st">'log_gdp_per_capita'</span>, <span class="st">'total_medals'</span>])</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">7</span>, <span class="dv">4</span>))</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>sns.regplot(data<span class="op">=</span>plot_data, x<span class="op">=</span><span class="st">'log_gdp_per_capita'</span>, y<span class="op">=</span><span class="st">'total_medals'</span>,</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>            scatter_kws<span class="op">=</span>{<span class="st">'alpha'</span>: <span class="fl">0.4</span>, <span class="st">'s'</span>: <span class="dv">25</span>, <span class="st">'color'</span>: BLUE},</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>            line_kws<span class="op">=</span>{<span class="st">'color'</span>: <span class="st">'red'</span>}, ax<span class="op">=</span>ax)</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"Wealthier Countries Win More Medals"</span>, fontsize<span class="op">=</span><span class="dv">14</span>, pad<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"Log GDP per Capita"</span>)</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">"Total Medals Won"</span>)</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>fig.tight_layout()</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/cell-12-output-1.png" width="655" height="366" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="home-advantage" class="level3">
<h3 class="anchored" data-anchor-id="home-advantage">5.5 Home Advantage</h3>
<p>To look at home advantage more directly, I compared each host nations medal count in the year they hosted against their average in all other Games, keeping the 15 nations that won the most medals whilst hosting. Most of them sit noticeably higher in the host year than their non-host average, the USA in 2002 and Norway in 1994 are both good examples of this. One thing to note is the chart orders by how many medals they won while hosting not by the size of the boost, so the nations on the left aren’t necessarily the ones who benefitted most.</p>
<div id="bc784e57" class="cell" data-execution_count="12">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>hosts <span class="op">=</span> (cy[cy[<span class="st">'is_host'</span>] <span class="op">==</span> <span class="dv">1</span>][[<span class="st">'noc'</span>, <span class="st">'year'</span>, <span class="st">'total_medals'</span>]].rename(columns<span class="op">=</span>{<span class="st">'total_medals'</span>: <span class="st">'host_medals'</span>}))</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>non_host_avg <span class="op">=</span> (cy[cy[<span class="st">'is_host'</span>] <span class="op">==</span> <span class="dv">0</span>].groupby(<span class="st">'noc'</span>)[<span class="st">'total_medals'</span>].mean().reset_index().rename(columns<span class="op">=</span>{<span class="st">'total_medals'</span>: <span class="st">'avg_non_host'</span>}))</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>compare <span class="op">=</span> (pd.merge(hosts, non_host_avg, on<span class="op">=</span><span class="st">'noc'</span>, how<span class="op">=</span><span class="st">'inner'</span>).sort_values(<span class="st">'host_medals'</span>, ascending<span class="op">=</span><span class="va">False</span>).head(<span class="dv">15</span>))</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="bu">long</span> <span class="op">=</span> compare.melt(id_vars<span class="op">=</span>[<span class="st">'noc'</span>],value_vars<span class="op">=</span>[<span class="st">'host_medals'</span>, <span class="st">'avg_non_host'</span>], var_name<span class="op">=</span><span class="st">'type'</span>, value_name<span class="op">=</span><span class="st">'medals'</span>)</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="bu">long</span>[<span class="st">'type'</span>] <span class="op">=</span> <span class="bu">long</span>[<span class="st">'type'</span>].<span class="bu">map</span>({<span class="st">'host_medals'</span>:  <span class="st">'Host Year'</span>,<span class="st">'avg_non_host'</span>: <span class="st">'Average Non-Host Year'</span>})</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">7</span>, <span class="dv">5</span>))</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>sns.barplot(data<span class="op">=</span><span class="bu">long</span>, x<span class="op">=</span><span class="st">'noc'</span>, y<span class="op">=</span><span class="st">'medals'</span>, hue<span class="op">=</span><span class="st">'type'</span>, ax<span class="op">=</span>ax)</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">'Medals when Hosting vs Not Hosting (Top 15 Host Nations)'</span>,fontsize<span class="op">=</span><span class="dv">14</span>, pad<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">'Country'</span>)</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">'Total Medals'</span>)</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>ax.tick_params(axis<span class="op">=</span><span class="st">'x'</span>, rotation<span class="op">=</span><span class="dv">45</span>)</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>fig.tight_layout()</span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/cell-13-output-1.png" width="655" height="462" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="what-the-regression-tells-us" class="level3">
<h3 class="anchored" data-anchor-id="what-the-regression-tells-us">5.6 What the regression tells us</h3>
<p>The coefficient plot pulls together the regression results, all three bars are to the right of zero, which means hosting, wealth and population all increase expected medal counts. The host status bar is actually the longest, with a coefficient of 4.6, though as I explain later that doesn’t mean it’s the most important factor overall, it just has the biggest per-unit jump. The black error bars show the 95% confidence intervals, so the shorter the error bar, the more precisely that effect has been estimated. GDP per capita has the tightest interval of the three, indicating it is the most reliably estimated of the three.</p>
<div id="b76db937" class="cell" data-execution_count="13">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>key_vars <span class="op">=</span> [<span class="st">'is_host'</span>, <span class="st">'log_gdp_per_capita'</span>, <span class="st">'log_population'</span>]</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>reg_plot <span class="op">=</span> reg[reg[<span class="st">'variable'</span>].isin(key_vars)].copy()</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>reg_plot[<span class="st">'variable'</span>] <span class="op">=</span> reg_plot[<span class="st">'variable'</span>].<span class="bu">map</span>({<span class="st">'is_host'</span>: <span class="st">'Host Country'</span>, <span class="st">'log_gdp_per_capita'</span>: <span class="st">'Log GDP per Capita'</span>, <span class="st">'log_population'</span>: <span class="st">'Log Population'</span>})</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">7</span>, <span class="dv">3</span>))</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>ax.barh(reg_plot[<span class="st">'variable'</span>], reg_plot[<span class="st">'Coef.'</span>])</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>ax.errorbar(reg_plot[<span class="st">'Coef.'</span>], reg_plot[<span class="st">'variable'</span>], xerr<span class="op">=</span>[</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>        reg_plot[<span class="st">'Coef.'</span>] <span class="op">-</span> reg_plot[<span class="st">'[0.025'</span>],</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>        reg_plot[<span class="st">'0.975]'</span>] <span class="op">-</span> reg_plot[<span class="st">'Coef.'</span>]],fmt<span class="op">=</span><span class="st">'none'</span>,color<span class="op">=</span><span class="st">'black'</span>,capsize<span class="op">=</span><span class="dv">4</span>)</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>ax.axvline(<span class="dv">0</span>, color<span class="op">=</span><span class="st">'black'</span>, linewidth<span class="op">=</span><span class="fl">0.8</span>)</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"What Predicts Winter Olympic Success?"</span>, fontsize<span class="op">=</span><span class="dv">14</span>, pad<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"Regression Coefficient (extra medals per unit increase)"</span>)</span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>fig.tight_layout()</span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/cell-14-output-1.png" width="653" height="270" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<hr>
</section>
</section>
<section id="conclusions" class="level2">
<h2 class="anchored" data-anchor-id="conclusions">6. Conclusions</h2>
<p>Three factors were tested: wealth, population size and hosting the Games. All three are statistically significant predictors of medal count.</p>
<section id="host-advantage-is-real-but-limited" class="level4">
<h4 class="anchored" data-anchor-id="host-advantage-is-real-but-limited">Host advantage is real but limited</h4>
<p>There is definitely a home advantage, on average, host countries win about 4.6 more medals than we would expect based on their wealth and population alone (p=0.015). So this is a genuine effect, you can see it in cases such as USA in 2002 (34 medals) and Norway in 1994 (26 medals). That said, this effect is quite limited, a country only hosts once in a while, so even though the boost is real, it only applies to a single Olympic Games at a time.</p>
</section>
<section id="gdp-per-capita-is-the-strongest-overall-predictor" class="level4">
<h4 class="anchored" data-anchor-id="gdp-per-capita-is-the-strongest-overall-predictor">GDP per capita is the strongest overall predictor</h4>
<p>From the regression, a 1 unit increase in log GDP per capita is associated with about 2.7 model medals (p &lt; 0.001). Which might not sound very large, however across the full range of countries in the dataset, it adds up to around a 16 medal difference between poorer and richer nations. This reflects the resources wealthy nations invest in training infrastructure, coaching and athlete development.</p>
</section>
<section id="why-the-host-bar-looks-largest-on-the-chart-but-isnt-the-strongest-predictor" class="level4">
<h4 class="anchored" data-anchor-id="why-the-host-bar-looks-largest-on-the-chart-but-isnt-the-strongest-predictor">Why the host bar looks largest on the chart but isn’t the strongest predictor</h4>
<p>On the coefficient plot, the host effect looks larger than GDP, which is misleading. The host coefficient (4.6) represents a one-time jump from not hosting to hosting. GDP on the other hand, applies to a variable that spans 6 units in the data, meaning its total real world effect (around 16 medals) is more than three times larger. The t-statistic for GDP (8.01) is also more than three times that of host status (2.44), confirming it is the more consistent and reliable predictor across the dataset</p>
</section>
<section id="population-matters-independently-of-wealth" class="level4">
<h4 class="anchored" data-anchor-id="population-matters-independently-of-wealth">Population matters independently of wealth</h4>
Population also plays an important role, even after accounting for wealth. A 1 unit increase in log population leads to about 1.4 additional medals (p &lt; 0.001). Across the full range of countries, this again adds up to roughly a 16 medal difference. So even though the effect per unit is smaller than GDP, the overall impact is similar due to population varying so much between countries.
<hr>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>